project_id = "saksjvmqyudkowxypoce"

[functions.send-notification-email]
verify_jwt = false

[functions.check-overdue-tasks]
verify_jwt = false

[functions.check-meeting-reminders]
verify_jwt = false

[functions.check-agreement-validity]
verify_jwt = false
