// AUTOGENERATED — do not edit by hand.
// Source: see supabase/functions/<name>/index.ts and supabase/functions/_shared/*.ts
// Regenerate with: ./scripts/bundle-edge-function.sh <entrypoint>
// This file is committed so the deployed edge function code is byte-reproducible
// from the repo even when shipping via the Supabase MCP single-file path.

// === supabase/functions/_shared/nameNormalization.ts ===
/** Deno-compatible copy of src/lib/nameNormalization.ts */

const CREDENTIAL_PATTERN =
  /\b(md|do|np|aprn|crnp|pa-c|pa|rn|bsn|msn|dnp|phd|fnp|fnp-c|fnp-bc|agacnp|agpcnp|pmhnp|crna|cnm|dnp-c|lcsw|lpc|mft|psyd)\b\.?/gi;

const SUFFIX_PATTERN = /\b(jr\.?|sr\.?|ii|iii|iv)\b\.?/gi;

const COMMA_LAST_FIRST = /^([^,]+),\s*(.+)$/;

export function canonicalName(raw: string | null | undefined): string {
  if (!raw) return '';
  let s = raw.trim();

  const commaMatch = COMMA_LAST_FIRST.exec(s);
  if (commaMatch) s = `${commaMatch[2].trim()} ${commaMatch[1].trim()}`;

  s = s.replace(CREDENTIAL_PATTERN, ' ');
  s = s.replace(SUFFIX_PATTERN, ' ');
  s = s.replace(/^dr\.?\s+/i, '');

  const parts = s.toLowerCase().replace(/[^a-z\s]/g, ' ').split(/\s+/).filter(Boolean);

  if (parts.length >= 3) {
    return `${parts[0]} ${parts[parts.length - 1]}`;
  }
  return parts.join(' ');
}

function jaccardBigrams(a: string, b: string): number {
  if (!a || !b) return 0;
  const bigrams = (s: string) => {
    const set = new Set<string>();
    for (let i = 0; i < s.length - 1; i++) set.add(s.slice(i, i + 2));
    return set;
  };
  const setA = bigrams(a);
  const setB = bigrams(b);
  const intersection = [...setA].filter(x => setB.has(x)).length;
  const union = new Set([...setA, ...setB]).size;
  return union === 0 ? 0 : intersection / union;
}

function levenshtein(a: string, b: string): number {
  const m = a.length, n = b.length;
  const dp: number[][] = Array.from({ length: m + 1 }, (_, i) =>
    Array.from({ length: n + 1 }, (_, j) => (i === 0 ? j : j === 0 ? i : 0))
  );
  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      dp[i][j] = a[i - 1] === b[j - 1]
        ? dp[i - 1][j - 1]
        : 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]);
    }
  }
  return dp[m][n];
}

export function fuzzyScore(a: string, b: string): number {
  const ca = canonicalName(a);
  const cb = canonicalName(b);
  if (!ca || !cb) return 0;
  if (ca === cb) return 1;
  const jaccard = jaccardBigrams(ca, cb);
  const maxLen = Math.max(ca.length, cb.length);
  const lev = maxLen === 0 ? 1 : 1 - levenshtein(ca, cb) / maxLen;
  return 0.6 * jaccard + 0.4 * lev;
}

export const FUZZY_MATCH_THRESHOLD = 0.85;
// === supabase/functions/_shared/availabilityOverrides.ts ===
/** Deno-compatible copy of src/config/availabilityOverrides.ts.
 *  Keep in sync with the canonical version. */

export interface ValidationConfig {
  /** Reject any single shift shorter than this after windowing. 0 disables. */
  min_single_shift_hours: number;
  /** Reject any single shift longer than this (after correction). */
  max_single_shift_hours: number;
  /** Flag if a single calendar date totals more than this. */
  max_daily_hours: number;
  /** Flag if any ISO week totals more than this. */
  max_weekly_hours: number;
  /** If false, end <= start is treated as an error (not a midnight crossing). */
  allow_overnight_shifts: boolean;
  /** Surface a warning when start is exactly 12:00 AM. */
  flag_midnight_start: boolean;
  /** Surface a warning when a recurring window covers ~the entire day. */
  flag_full_day_availability: boolean;
  /** Operating-hours window in minutes from midnight (ET). Shifts outside the
   *  window are clamped (partial overlap) or cut entirely (no overlap).
   *  Tracked in `hours_removed_for_operating_hours`. */
  weekday_window_start_min: number;
  weekday_window_end_min: number;
  weekend_window_start_min: number;
  weekend_window_end_min: number;
}

export const DEFAULT_VALIDATION_CONFIG: ValidationConfig = {
  min_single_shift_hours: 0,
  max_single_shift_hours: 12,
  max_daily_hours: 12,
  max_weekly_hours: 60,
  allow_overnight_shifts: false,
  flag_midnight_start: true,
  flag_full_day_availability: true,
  // 9:00 AM - 9:00 PM ET on weekdays, 9:00 AM - 12:00 PM ET on weekends.
  weekday_window_start_min: 540,
  weekday_window_end_min: 1260,
  weekend_window_start_min: 540,
  weekend_window_end_min: 720,
};

export interface ProviderOverrideRule {
  /** Optional: only match this kind of interval. */
  kind?: 'recurring' | 'one_off' | 'in_home';
  /** Optional: only match this weekday (case-insensitive). */
  dayOfWeek?: string;
  /** Raw start/end as the provider entered them on the Jotform widget. */
  rawStart: string;
  rawEnd: string;
  /** Corrected start/end. */
  normalizedStart: string;
  normalizedEnd: string;
  /** Free-form note explaining the correction (shows up in the audit log). */
  reason?: string;
}

export interface ProviderOverride {
  /** Display name — included for human readability in logs. */
  fullName?: string;
  /** Most stable matcher; preferred. */
  email?: string;
  /** Provider UUID, if known. */
  providerId?: string;
  rules: ProviderOverrideRule[];
}

/**
 * Default overrides keyed off ClinOps's May 2026 audit of bad submissions.
 * Add new entries here rather than encoding fixes inside the validator.
 */
export const AVAILABILITY_OVERRIDES: ProviderOverride[] = [
  {
    fullName: 'Cassondra Hawkins',
    rules: [
      {
        kind: 'recurring',
        dayOfWeek: 'Friday',
        rawStart: '4:00 AM',
        rawEnd: '9:00 PM',
        normalizedStart: '4:00 PM',
        normalizedEnd: '9:00 PM',
        reason: 'Cassondra Hawkins Friday: confirmed afternoon-only availability; 4 AM is an AM/PM entry error',
      },
      {
        kind: 'recurring',
        dayOfWeek: 'Sunday',
        rawStart: '9:00 AM',
        rawEnd: '12:00 AM',
        normalizedStart: '9:00 AM',
        normalizedEnd: '12:00 PM',
        reason: 'Cassondra Hawkins Sunday: confirmed morning-only availability; 12 AM end is an AM/PM entry error',
      },
    ],
  },
  {
    fullName: 'Akosua Norgbey',
    rules: [
      {
        rawStart: '8:00 AM',
        rawEnd: '11:59 PM',
        normalizedStart: '8:00 AM',
        normalizedEnd: '12:00 PM',
        reason: 'Akosua Norgbey: confirmed morning-only window; do not credit full-day capacity',
      },
    ],
  },
  {
    fullName: 'Melissa Harris-Perotti',
    rules: [
      {
        rawStart: '12:00 AM',
        rawEnd: '6:00 PM',
        normalizedStart: '12:00 PM',
        normalizedEnd: '6:00 PM',
        reason: 'Melissa Harris-Perotti: confirmed afternoon-only availability; 12 AM start is an AM/PM entry error',
      },
    ],
  },
  {
    fullName: 'Shadae McMillan',
    rules: [
      {
        rawStart: '12:00 AM',
        rawEnd: '3:00 PM',
        normalizedStart: '12:00 PM',
        normalizedEnd: '3:00 PM',
        reason: 'Shadae McMillan: confirmed afternoon-only availability; 12 AM start is an AM/PM entry error',
      },
    ],
  },
];
// === supabase/functions/_shared/availabilityValidation.ts ===
/** Deno-compatible copy of src/lib/availabilityValidation.ts.
 *
 * Keep in sync with the canonical version. Edge functions
 * (sync-jotform-submissions, evaluate-schedule-submissions) import from here. */

export type ValidationStatus =
  | 'valid'
  | 'auto_corrected'
  | 'needs_review'
  | 'rejected_or_unusable';

export type CorrectionConfidence = 'high' | 'medium' | 'low' | 'none';

export type IntervalKind = 'recurring' | 'one_off' | 'in_home';

/** Input to validation; comes from the parsed Jotform widget. */
export interface RawInterval {
  kind: IntervalKind;
  /** Recurring entries identify a weekday (e.g. "Monday"). */
  dayOfWeek?: string;
  /** One-off and in-home entries identify a calendar date (YYYY-MM-DD). */
  date?: string;
  /** Raw "09:00 AM" / "5:00 PM" / "13:00" strings as submitted. */
  rawStart: string;
  rawEnd: string;
  /** Submission ID, for audit linkage. */
  submissionId?: string;
  /** Provider display name, for the report. */
  providerName?: string;
}

export interface NormalizedInterval {
  kind: IntervalKind;
  dayOfWeek?: string;
  date?: string;
  raw_start_time: string;
  raw_end_time: string;
  /** "HH:MM AM/PM" canonical form of the corrected start. */
  normalized_start_time: string;
  normalized_end_time: string;
  original_duration_hours: number | null;
  normalized_duration_hours: number | null;
  validation_status: ValidationStatus;
  validation_warnings: string[];
  correction_reason: string | null;
  correction_confidence: CorrectionConfidence;
  /** Whether the evaluator should use this interval when allocating demand. */
  used_in_forecast: boolean;
  needs_manual_review: boolean;
  submissionId?: string;
  providerName?: string;
  /** Internal: corrected time as minutes from midnight, for downstream merge. */
  normalized_start_min: number | null;
  normalized_end_min: number | null;
}

export interface ProviderIdentity {
  providerId?: string | null;
  email?: string | null;
  name?: string | null;
}

export interface NormalizationSummary {
  raw_total_hours: number;
  normalized_total_hours: number;
  hours_removed_for_unavailability: number;
  hours_removed_for_duplicates: number;
  /** Hours dropped or trimmed because the slot fell outside the configured
   *  operating-hours window (default 9 AM - 9 PM ET weekdays, 9 AM - 12 PM ET
   *  weekends). */
  hours_removed_for_operating_hours: number;
  /** Hours dropped because a window is shorter than the configured minimum
   *  shift length. Used for MH coaching's 2.5h minimum. */
  hours_removed_for_minimum_shift: number;
  hours_changed_by_validation: number;
  intervals_auto_corrected: number;
  intervals_needing_review: number;
  intervals_rejected: number;
  /** Sum of timeline slots across ALL kinds (telehealth + in-home/clinic). */
  total_normalized_timeline_hours: number;
  /** Sum of timeline slots restricted to forecastKinds (default telehealth-only). */
  final_approvable_hours: number;
}

export interface ValidationReportRow {
  provider: string | null;
  submission_id: string | null;
  date: string | null;
  day_of_week: string | null;
  raw_time_range: string;
  corrected_time_range: string;
  raw_duration: number | null;
  corrected_duration: number | null;
  warnings: string[];
  correction_reason: string | null;
  used_in_forecast: boolean;
  needs_manual_review: boolean;
  validation_status: ValidationStatus;
}

// ─── Time parsing & formatting ────────────────────────────────────────────

interface ParsedTime {
  /** Minutes from midnight, 0..1440. 24:00 stays as 1440 only when input was 24:00. */
  totalMinutes: number;
  hour: number;
  minute: number;
  ampm: 'AM' | 'PM' | null;
}

/** Parses "09:00 AM", "5:00 PM", "13:00", "11:59 PM" → ParsedTime. */
export function parseTimeOfDay(raw: string | null | undefined): ParsedTime | null {
  if (raw == null) return null;
  const m = String(raw).trim().match(/^(\d{1,2}):(\d{2})\s*(AM|PM)?\s*$/i);
  if (!m) return null;
  let h = Number(m[1]);
  const min = Number(m[2]);
  const ampmRaw = (m[3] ?? '').toUpperCase();
  const ampm: 'AM' | 'PM' | null = ampmRaw === 'AM' ? 'AM' : ampmRaw === 'PM' ? 'PM' : null;
  if (ampm === 'AM') {
    if (h === 12) h = 0;
  } else if (ampm === 'PM') {
    if (h !== 12) h += 12;
  }
  if (h < 0 || h > 24 || min < 0 || min >= 60) return null;
  return { totalMinutes: h * 60 + min, hour: h, minute: min, ampm };
}

/** Format minutes-from-midnight as "h:mm AM/PM" canonical string. */
export function formatTime(totalMinutes: number): string {
  const safe = ((totalMinutes % 1440) + 1440) % 1440;
  const h24 = Math.floor(safe / 60);
  const m = safe % 60;
  const ampm = h24 < 12 ? 'AM' : 'PM';
  let h12 = h24 % 12;
  if (h12 === 0) h12 = 12;
  return `${h12}:${String(m).padStart(2, '0')} ${ampm}`;
}

/** Difference end - start, treating end <= start as overnight (+24h). */
export function intervalHours(startMin: number, endMin: number): number {
  let diff = endMin - startMin;
  if (diff <= 0) diff += 24 * 60;
  return diff / 60;
}

// ─── Override matching ────────────────────────────────────────────────────

/**
 * Resolve a provider's override rules using the most stable identifier
 * available: email first (most stable), then provider UUID, then a
 * canonicalized full name match. Returns null if no override exists.
 */
export function findProviderOverride(
  identity: ProviderIdentity,
  overrides: ProviderOverride[] = AVAILABILITY_OVERRIDES,
): ProviderOverride | null {
  const email = (identity.email ?? '').trim().toLowerCase();
  if (email) {
    const byEmail = overrides.find(o => (o.email ?? '').toLowerCase() === email);
    if (byEmail) return byEmail;
  }
  if (identity.providerId) {
    const byId = overrides.find(o => o.providerId === identity.providerId);
    if (byId) return byId;
  }
  const canon = canonicalName(identity.name ?? '');
  if (canon) {
    const byName = overrides.find(o => canonicalName(o.fullName ?? '') === canon);
    if (byName) return byName;
  }
  return null;
}

/**
 * Attempt to match a raw interval against one of a provider's override
 * rules. Match keys: rawStart + rawEnd, plus optional dayOfWeek and kind.
 */
function matchOverrideRule(
  raw: RawInterval,
  override: ProviderOverride | null,
): ProviderOverrideRule | null {
  if (!override) return null;
  const rawStartNorm = canonicalTimeKey(raw.rawStart);
  const rawEndNorm = canonicalTimeKey(raw.rawEnd);
  for (const rule of override.rules) {
    const ruleStart = canonicalTimeKey(rule.rawStart);
    const ruleEnd = canonicalTimeKey(rule.rawEnd);
    if (ruleStart !== rawStartNorm || ruleEnd !== rawEndNorm) continue;
    if (rule.kind && rule.kind !== raw.kind) continue;
    if (rule.dayOfWeek && (raw.dayOfWeek ?? '').toLowerCase() !== rule.dayOfWeek.toLowerCase()) {
      continue;
    }
    return rule;
  }
  return null;
}

function canonicalTimeKey(t: string | undefined | null): string {
  const p = parseTimeOfDay(t ?? '');
  if (!p) return String(t ?? '').trim().toLowerCase();
  return formatTime(p.totalMinutes).toLowerCase();
}

// ─── Per-interval validation ──────────────────────────────────────────────

interface DefaultCorrectionResult {
  correctedStartMin: number;
  correctedEndMin: number;
  reason: string;
  confidence: CorrectionConfidence;
}

/**
 * Apply built-in deterministic AM/PM corrections that don't need a
 * provider-specific override. These are intentionally conservative:
 * each rule combines a pattern in the raw entry with an additional
 * implausibility signal (oversize duration or full-day recurring) so
 * we don't silently rewrite legitimate shifts.
 */
function applyDefaultCorrection(
  raw: RawInterval,
  startMin: number,
  endMin: number,
  config: ValidationConfig,
): DefaultCorrectionResult | null {
  const rawDuration = intervalHours(startMin, endMin);

  // Rule: 12:00 AM start with afternoon/evening end → start was meant as 12 PM.
  // Examples: 12:00 AM–3:00 PM → 12:00 PM–3:00 PM; 12:00 AM–6:00 PM → 12:00 PM–6:00 PM.
  if (
    config.flag_midnight_start &&
    startMin === 0 &&
    endMin >= 12 * 60 + 1 && // anything past noon
    endMin <= 22 * 60 // sanity cap
  ) {
    return {
      correctedStartMin: 12 * 60,
      correctedEndMin: endMin,
      reason: '12:00 AM start with afternoon/evening end normalized to 12:00 PM (likely AM/PM entry error)',
      confidence: 'high',
    };
  }

  // Rule: very early AM start (1–5 AM) paired with evening end is almost
  // always an AM/PM error on the start. e.g. 4:00 AM–9:00 PM → 4:00 PM–9:00 PM.
  // Trigger only if the resulting raw shift would exceed the single-shift cap.
  if (
    startMin >= 60 && startMin < 5 * 60 &&
    endMin >= 17 * 60 &&
    rawDuration > config.max_single_shift_hours
  ) {
    return {
      correctedStartMin: startMin + 12 * 60,
      correctedEndMin: endMin,
      reason: `Early-AM start (${formatTime(startMin)}) with evening end exceeds ${config.max_single_shift_hours}h; normalized start to PM`,
      confidence: 'medium',
    };
  }

  // Rule: end at 12:00 AM with morning start almost always means 12:00 PM.
  // e.g. 9:00 AM–12:00 AM → 9:00 AM–12:00 PM. Only fires when overnight is
  // disallowed AND the overnight reading would exceed max_single_shift.
  if (
    !config.allow_overnight_shifts &&
    endMin === 0 &&
    startMin >= 6 * 60 && startMin <= 11 * 60
  ) {
    const overnightDuration = intervalHours(startMin, endMin); // wraps to next day
    if (overnightDuration > config.max_single_shift_hours) {
      return {
        correctedStartMin: startMin,
        correctedEndMin: 12 * 60,
        reason: `Morning start with 12:00 AM end would be ${overnightDuration.toFixed(1)}h overnight; normalized end to 12:00 PM`,
        confidence: 'medium',
      };
    }
  }

  return null;
}

/**
 * Validate and (if applicable) correct a single raw interval.
 *
 * Order of precedence:
 *   1. Provider-specific override rule (highest authority).
 *   2. Default deterministic AM/PM corrections.
 *   3. Otherwise: keep raw, but flag warnings.
 */
export function validateInterval(
  raw: RawInterval,
  config: ValidationConfig = DEFAULT_VALIDATION_CONFIG,
  override: ProviderOverride | null = null,
): NormalizedInterval {
  const warnings: string[] = [];
  const startParsed = parseTimeOfDay(raw.rawStart);
  const endParsed = parseTimeOfDay(raw.rawEnd);

  // Malformed times are unusable.
  if (!startParsed || !endParsed) {
    return buildNormalized(raw, {
      startMin: 0,
      endMin: 0,
      normalizedStartMin: null,
      normalizedEndMin: null,
      originalDuration: null,
      normalizedDuration: null,
      status: 'rejected_or_unusable',
      warnings: ['Malformed or unparseable time string'],
      reason: null,
      confidence: 'none',
      usedInForecast: false,
      needsReview: true,
    });
  }

  const startMin = startParsed.totalMinutes;
  const endMin = endParsed.totalMinutes;

  // Original duration: we treat end <= start as overnight here for the audit
  // value (so we report what the provider literally typed).
  const originalDuration = intervalHours(startMin, endMin);

  // 1) Provider-specific override
  const overrideRule = matchOverrideRule(raw, override);
  if (overrideRule) {
    const ovStart = parseTimeOfDay(overrideRule.normalizedStart);
    const ovEnd = parseTimeOfDay(overrideRule.normalizedEnd);
    if (ovStart && ovEnd) {
      const newDuration = intervalHours(ovStart.totalMinutes, ovEnd.totalMinutes);
      const status: ValidationStatus = 'auto_corrected';
      warnings.push(`Provider-specific override applied: ${overrideRule.reason ?? 'configured rule'}`);
      return buildNormalized(raw, {
        startMin,
        endMin,
        normalizedStartMin: ovStart.totalMinutes,
        normalizedEndMin: ovEnd.totalMinutes,
        originalDuration,
        normalizedDuration: newDuration,
        status,
        warnings,
        reason: `provider_override: ${overrideRule.reason ?? `${formatTime(startMin)}-${formatTime(endMin)} → ${formatTime(ovStart.totalMinutes)}-${formatTime(ovEnd.totalMinutes)}`}`,
        confidence: 'high',
      });
    }
  }

  // Detect "full-day recurring availability" before default correction so we
  // can flag it for review when no override mapped it to a real window.
  const isFullDayRecurring =
    raw.kind === 'recurring' &&
    config.flag_full_day_availability &&
    isFullDayWindow(startMin, endMin);

  if (isFullDayRecurring) {
    warnings.push('Recurring availability spans nearly the entire day (e.g. 8 AM–11:59 PM); flagged for review unless a provider-specific override is configured');
  }

  // 2) Default deterministic correction
  const defaultCorrection = applyDefaultCorrection(raw, startMin, endMin, config);
  if (defaultCorrection && !isFullDayRecurring) {
    const newDuration = intervalHours(defaultCorrection.correctedStartMin, defaultCorrection.correctedEndMin);
    warnings.push(defaultCorrection.reason);
    // Re-run sanity checks against the corrected window
    const correctedWarnings = collectShiftWarnings(
      defaultCorrection.correctedStartMin,
      defaultCorrection.correctedEndMin,
      config,
    );
    for (const w of correctedWarnings) warnings.push(`(post-correction) ${w}`);
    return buildNormalized(raw, {
      startMin,
      endMin,
      normalizedStartMin: defaultCorrection.correctedStartMin,
      normalizedEndMin: defaultCorrection.correctedEndMin,
      originalDuration,
      normalizedDuration: newDuration,
      status: 'auto_corrected',
      warnings,
      reason: defaultCorrection.reason,
      confidence: defaultCorrection.confidence,
    });
  }

  // 3) No correction — apply raw checks
  for (const w of collectShiftWarnings(startMin, endMin, config)) warnings.push(w);

  // End <= start: overnight handling
  let status: ValidationStatus = 'valid';
  const normalizedStartMin: number | null = startMin;
  const normalizedEndMin: number | null = endMin;
  const normalizedDuration: number | null = originalDuration;
  const reason: string | null = null;
  const confidence: CorrectionConfidence = 'none';
  let usedInForecast = true;
  let needsReview = false;

  if (endMin <= startMin) {
    if (config.allow_overnight_shifts) {
      warnings.push('Overnight shift accepted (allow_overnight_shifts=true)');
    } else {
      warnings.push('End time is at or before start time and overnight shifts are not allowed; flagged for review');
      status = 'needs_review';
      needsReview = true;
      usedInForecast = false;
    }
  }

  if (isFullDayRecurring) {
    status = 'needs_review';
    needsReview = true;
    usedInForecast = false;
  }

  if (originalDuration > config.max_single_shift_hours) {
    warnings.push(`Single shift duration ${originalDuration.toFixed(2)}h exceeds max_single_shift_hours=${config.max_single_shift_hours}h`);
    if (status === 'valid') {
      status = 'needs_review';
      needsReview = true;
      usedInForecast = false;
    }
  }

  return buildNormalized(raw, {
    startMin,
    endMin,
    normalizedStartMin,
    normalizedEndMin,
    originalDuration,
    normalizedDuration,
    status,
    warnings,
    reason,
    confidence,
    usedInForecast,
    needsReview,
  });
}

function isFullDayWindow(startMin: number, endMin: number): boolean {
  // Treat any window covering >= 14 hours within a single day starting before
  // 9 AM and ending at/after 23:30 as "full-day" for review-flag purposes.
  if (endMin <= startMin) return false;
  const dur = (endMin - startMin) / 60;
  return startMin <= 9 * 60 && endMin >= 23 * 60 + 30 && dur >= 14;
}

function collectShiftWarnings(startMin: number, endMin: number, config: ValidationConfig): string[] {
  const out: string[] = [];
  if (config.flag_midnight_start && startMin === 0 && endMin > 0 && endMin <= 22 * 60) {
    out.push('Start time is 12:00 AM with non-overnight end — likely AM/PM entry error');
  }
  if (config.flag_full_day_availability && isFullDayWindow(startMin, endMin)) {
    out.push('Window spans nearly the entire day');
  }
  return out;
}

interface BuildArgs {
  startMin: number;
  endMin: number;
  normalizedStartMin: number | null;
  normalizedEndMin: number | null;
  originalDuration: number | null;
  normalizedDuration: number | null;
  status: ValidationStatus;
  warnings: string[];
  reason: string | null;
  confidence: CorrectionConfidence;
  usedInForecast?: boolean;
  needsReview?: boolean;
}

function buildNormalized(raw: RawInterval, args: BuildArgs): NormalizedInterval {
  const usedInForecast =
    args.usedInForecast ??
    (args.status === 'valid' || args.status === 'auto_corrected');
  const needsReview =
    args.needsReview ?? args.status === 'needs_review';
  return {
    kind: raw.kind,
    dayOfWeek: raw.dayOfWeek,
    date: raw.date,
    raw_start_time: raw.rawStart,
    raw_end_time: raw.rawEnd,
    normalized_start_time:
      args.normalizedStartMin == null ? raw.rawStart : formatTime(args.normalizedStartMin),
    normalized_end_time:
      args.normalizedEndMin == null ? raw.rawEnd : formatTime(args.normalizedEndMin),
    original_duration_hours:
      args.originalDuration == null ? null : round2(args.originalDuration),
    normalized_duration_hours:
      args.normalizedDuration == null ? null : round2(args.normalizedDuration),
    validation_status: args.status,
    validation_warnings: args.warnings,
    correction_reason: args.reason,
    correction_confidence: args.confidence,
    used_in_forecast: usedInForecast,
    needs_manual_review: needsReview,
    submissionId: raw.submissionId,
    providerName: raw.providerName,
    normalized_start_min: args.normalizedStartMin,
    normalized_end_min: args.normalizedEndMin,
  };
}

// ─── Pipeline-level helpers ───────────────────────────────────────────────

/**
 * Date-level expansion of a normalized interval into one (date, startMin, endMin)
 * tuple per matching weekday in the target month, with overnight crossings split.
 * Returns an empty array for intervals not used in forecast.
 */
export interface ExpandedSlot {
  date: string; // YYYY-MM-DD
  startMin: number;
  endMin: number; // > startMin
  source: NormalizedInterval;
}

const DAY_TO_INDEX: Record<string, number> = {
  sunday: 0, monday: 1, tuesday: 2, wednesday: 3,
  thursday: 4, friday: 5, saturday: 6,
};

export function weekdayDatesInMonth(dayName: string, monthISO: string): string[] {
  const dayIdx = DAY_TO_INDEX[String(dayName).trim().toLowerCase()];
  if (dayIdx === undefined) return [];
  const [y, m] = monthISO.split('-').map(Number);
  const firstWeekday = new Date(Date.UTC(y, m - 1, 1)).getUTCDay();
  const daysInMonth = new Date(Date.UTC(y, m, 0)).getUTCDate();
  const offset = (dayIdx - firstWeekday + 7) % 7;
  const out: string[] = [];
  for (let day = 1 + offset; day <= daysInMonth; day += 7) {
    out.push(`${y}-${String(m).padStart(2, '0')}-${String(day).padStart(2, '0')}`);
  }
  return out;
}

export function nextDate(dateISO: string): string | null {
  const d = new Date(dateISO + 'T00:00:00Z');
  if (isNaN(d.getTime())) return null;
  d.setUTCDate(d.getUTCDate() + 1);
  return d.toISOString().slice(0, 10);
}

export function expandNormalizedToSlots(
  normalized: NormalizedInterval,
  targetMonth: string,
): ExpandedSlot[] {
  if (!normalized.used_in_forecast) return [];
  if (normalized.normalized_start_min == null || normalized.normalized_end_min == null) return [];
  const startMin = normalized.normalized_start_min;
  const endMin = normalized.normalized_end_min;

  const dates: string[] = [];
  if (normalized.kind === 'recurring' && normalized.dayOfWeek) {
    dates.push(...weekdayDatesInMonth(normalized.dayOfWeek, targetMonth));
  } else if (normalized.date) {
    if (isInMonth(normalized.date, targetMonth)) dates.push(normalized.date);
  }

  const slots: ExpandedSlot[] = [];
  for (const date of dates) {
    if (endMin <= startMin) {
      slots.push({ date, startMin, endMin: 1440, source: normalized });
      const next = nextDate(date);
      if (next && isInMonth(next, targetMonth)) {
        slots.push({ date: next, startMin: 0, endMin, source: normalized });
      }
    } else {
      slots.push({ date, startMin, endMin, source: normalized });
    }
  }
  return slots;
}

/** Apply the operating-hours window to a stream of expanded slots, clamping
 *  partial overlaps and dropping fully out-of-window slots. Returns the
 *  surviving slots (possibly clamped), the original portions that were
 *  dropped/trimmed (so downstream can emit per-shift "declined: outside
 *  business hours" rows), and the total hours removed. The source
 *  NormalizedInterval is preserved for downstream linkage; in-home /
 *  clinic shifts are NOT subject to this filter (their location is fixed
 *  outside the telehealth ops window). */
export function applyOperatingHoursWindow(
  slots: ExpandedSlot[],
  config: ValidationConfig,
): { slots: ExpandedSlot[]; droppedSlots: ExpandedSlot[]; hoursRemoved: number } {
  const out: ExpandedSlot[] = [];
  const dropped: ExpandedSlot[] = [];
  let removed = 0;
  for (const s of slots) {
    if (s.source.kind === 'in_home') {
      out.push(s);
      continue;
    }
    const d = new Date(s.date + 'T00:00:00Z');
    const dow = d.getUTCDay();
    const isWeekend = dow === 0 || dow === 6;
    const winStart = isWeekend ? config.weekend_window_start_min : config.weekday_window_start_min;
    const winEnd = isWeekend ? config.weekend_window_end_min : config.weekday_window_end_min;

    const rawHours = (s.endMin - s.startMin) / 60;
    if (s.endMin <= winStart || s.startMin >= winEnd) {
      removed += rawHours;
      dropped.push(s);
      continue;
    }
    const newStart = Math.max(s.startMin, winStart);
    const newEnd = Math.min(s.endMin, winEnd);
    if (newEnd <= newStart) {
      removed += rawHours;
      dropped.push(s);
      continue;
    }
    if (newStart === s.startMin && newEnd === s.endMin) {
      out.push(s);
    } else {
      removed += ((newStart - s.startMin) + (s.endMin - newEnd)) / 60;
      out.push({ ...s, startMin: newStart, endMin: newEnd });
      if (newStart > s.startMin) {
        dropped.push({ ...s, startMin: s.startMin, endMin: newStart });
      }
      if (newEnd < s.endMin) {
        dropped.push({ ...s, startMin: newEnd, endMin: s.endMin });
      }
    }
  }
  return { slots: out, droppedSlots: dropped, hoursRemoved: round2(removed) };
}

export function applyMinimumShiftLength(
  slots: ExpandedSlot[],
  config: ValidationConfig,
): { slots: ExpandedSlot[]; droppedSlots: ExpandedSlot[]; hoursRemoved: number } {
  const minHours = Number(config.min_single_shift_hours ?? 0);
  if (!Number.isFinite(minHours) || minHours <= 0) {
    return { slots, droppedSlots: [], hoursRemoved: 0 };
  }

  const out: ExpandedSlot[] = [];
  const dropped: ExpandedSlot[] = [];
  let removed = 0;
  for (const s of slots) {
    const hours = (s.endMin - s.startMin) / 60;
    if (hours + 0.001 < minHours) {
      removed += hours;
      dropped.push(s);
    } else {
      out.push(s);
    }
  }
  return { slots: out, droppedSlots: dropped, hoursRemoved: round2(removed) };
}

function isInMonth(dateISO: string, monthISO: string): boolean {
  return dateISO >= monthISO && dateISO < nextMonth(monthISO);
}

function nextMonth(monthISO: string): string {
  const [y, m] = monthISO.split('-').map(Number);
  const ny = m === 12 ? y + 1 : y;
  const nm = m === 12 ? 1 : m + 1;
  return `${ny}-${String(nm).padStart(2, '0')}-01`;
}

// ─── Dedup / merge / unavailable subtraction ──────────────────────────────

export interface ReconciledTimeline {
  /** One slot per (date, start, end) — duplicates collapsed, later submissions
   *  overwrite earlier overlapping slots. */
  slots: ExpandedSlot[];
  hours_removed_for_duplicates: number;
  hours_removed_for_unavailability: number;
  intervals_overlapping_unavailable: ExpandedSlot[];
}

export interface DatedSlotInput extends ExpandedSlot {
  submittedAt?: string; // ISO; later wins
}

/**
 * Merge a stream of expanded slots from one or more submissions for the same
 * provider+month. Behaviour:
 *   - Slots are processed chronologically by submittedAt.
 *   - When a new slot overlaps an existing slot on the same date, the new
 *     slot wins; the existing slot is trimmed or dropped.
 *   - Identical (date, start, end) duplicates collapse silently.
 *   - hours_removed_for_duplicates accumulates the hours that were dropped
 *     because a later slot covered them.
 *   - Unavailable dates passed in are subtracted AFTER merge.
 */
export function reconcileTimeline(
  inputs: DatedSlotInput[],
  unavailableDates: string[] = [],
): ReconciledTimeline {
  const sorted = [...inputs].sort((a, b) =>
    (a.submittedAt ?? '').localeCompare(b.submittedAt ?? '') ||
    a.date.localeCompare(b.date) ||
    a.startMin - b.startMin,
  );

  let timeline: ExpandedSlot[] = [];
  let dupHours = 0;

  for (const incoming of sorted) {
    const before = totalHours(timeline);
    timeline = mergeSlot(timeline, incoming);
    const after = totalHours(timeline);
    const incomingHours = (incoming.endMin - incoming.startMin) / 60;
    const delta = before + incomingHours - after; // positive = displaced existing
    if (delta > 0.001) dupHours += delta;
  }

  const unavailable = new Set(unavailableDates);
  let unavailHours = 0;
  const overlappingUnavailable: ExpandedSlot[] = [];
  const filtered: ExpandedSlot[] = [];
  for (const s of timeline) {
    if (unavailable.has(s.date)) {
      unavailHours += (s.endMin - s.startMin) / 60;
      overlappingUnavailable.push(s);
      continue;
    }
    filtered.push(s);
  }

  return {
    slots: filtered,
    hours_removed_for_duplicates: round2(dupHours),
    hours_removed_for_unavailability: round2(unavailHours),
    intervals_overlapping_unavailable: overlappingUnavailable,
  };
}

function mergeSlot(timeline: ExpandedSlot[], incoming: ExpandedSlot): ExpandedSlot[] {
  const out: ExpandedSlot[] = [];
  for (const existing of timeline) {
    if (existing.date !== incoming.date || !overlaps(existing, incoming)) {
      out.push(existing);
      continue;
    }
    if (existing.startMin < incoming.startMin) {
      out.push({ ...existing, endMin: incoming.startMin });
    }
    if (existing.endMin > incoming.endMin) {
      out.push({ ...existing, startMin: incoming.endMin });
    }
  }
  out.push(incoming);
  return out;
}

function overlaps(a: ExpandedSlot, b: ExpandedSlot): boolean {
  return a.startMin < b.endMin && b.startMin < a.endMin;
}

function totalHours(slots: ExpandedSlot[]): number {
  return slots.reduce((sum, s) => sum + (s.endMin - s.startMin) / 60, 0);
}

// ─── Top-level pipeline ───────────────────────────────────────────────────

export interface NormalizationInput {
  identity: ProviderIdentity;
  /** Each submission contributes intervals tagged with submittedAt. */
  submissions: Array<{
    submissionId: string;
    submittedAt: string; // ISO
    intervals: RawInterval[];
  }>;
  targetMonth: string; // YYYY-MM-01
  unavailableDates?: string[];
  config?: ValidationConfig;
  overrides?: ProviderOverride[];
  /**
   * Interval kinds that count toward `summary.final_approvable_hours`.
   * Default: ['recurring', 'one_off'] — i.e. telehealth only. In-home /
   * clinic shifts are scoped separately and do not consume telehealth
   * demand-hour gaps. Pass ['recurring','one_off','in_home'] to opt in.
   * The full normalized `timeline` always contains every kind so downstream
   * shift recommendations can still publish in-home shifts.
   */
  forecastKinds?: IntervalKind[];
}

export interface NormalizationResult {
  identity: ProviderIdentity;
  targetMonth: string;
  normalized: NormalizedInterval[];
  timeline: ExpandedSlot[];
  /** Original portions of slots that were dropped/trimmed by the operating-
   *  hours window (9a-9p ET weekdays, 9a-12p ET weekends). Each entry is
   *  the original out-of-window fragment with its source NormalizedInterval
   *  preserved, so downstream can emit "declined: outside business hours"
   *  per-shift rows. */
  outOfHoursTimeline: ExpandedSlot[];
  /** Slots dropped because they are shorter than the configured minimum shift
   *  length. These can be emitted as explicit cut rows downstream. */
  policyCutTimeline: ExpandedSlot[];
  summary: NormalizationSummary;
  report: ValidationReportRow[];
  override_used: ProviderOverride | null;
}

/**
 * Full pipeline: validate → normalize → expand → reconcile (dedup/unavail) →
 * summarize. The slots/timeline output is what evaluate-schedule-submissions
 * should consume for forecast approve/deny — they reflect corrected times.
 */
export function normalizeProviderAvailability(input: NormalizationInput): NormalizationResult {
  const config = input.config ?? DEFAULT_VALIDATION_CONFIG;
  const overrides = input.overrides ?? AVAILABILITY_OVERRIDES;
  const override = findProviderOverride(input.identity, overrides);

  const normalized: NormalizedInterval[] = [];
  const slotInputs: DatedSlotInput[] = [];
  let rawTotal = 0;

  for (const sub of input.submissions) {
    for (const raw of sub.intervals) {
      const tagged: RawInterval = { ...raw, submissionId: sub.submissionId, providerName: input.identity.name ?? raw.providerName };
      const norm = validateInterval(tagged, config, override);
      normalized.push(norm);
      if (norm.original_duration_hours != null) rawTotal += norm.original_duration_hours;

      const slots = expandNormalizedToSlots(norm, input.targetMonth);
      for (const s of slots) slotInputs.push({ ...s, submittedAt: sub.submittedAt });

      // Out-of-month detection for one-off / in-home with explicit dates
      if ((norm.kind === 'one_off' || norm.kind === 'in_home') && norm.date) {
        if (!isInMonth(norm.date, input.targetMonth)) {
          norm.validation_warnings.push(`Date ${norm.date} is outside target month ${input.targetMonth}`);
          if (norm.validation_status === 'valid' || norm.validation_status === 'auto_corrected') {
            norm.validation_status = 'needs_review';
            norm.needs_manual_review = true;
            norm.used_in_forecast = false;
          }
        }
      }
    }
  }

  const windowed = applyOperatingHoursWindow(slotInputs, config);
  const minimumLength = applyMinimumShiftLength(windowed.slots, config);
  const windowedSlotInputs: DatedSlotInput[] = minimumLength.slots.map(s => {
    const orig = slotInputs.find(
      o => o.date === s.date && o.source === s.source,
    );
    return { ...s, submittedAt: orig?.submittedAt };
  });
  const reconciled = reconcileTimeline(windowedSlotInputs, input.unavailableDates ?? []);

  const normalizedTotal = normalized.reduce(
    (sum, n) => sum + (n.normalized_duration_hours ?? 0),
    0,
  );
  const hoursChanged = normalized.reduce((sum, n) => {
    if (n.normalized_duration_hours == null || n.original_duration_hours == null) return sum;
    return sum + Math.abs(n.normalized_duration_hours - n.original_duration_hours);
  }, 0);

  const forecastKinds = new Set<IntervalKind>(input.forecastKinds ?? ['recurring', 'one_off']);
  const totalTimelineHours = round2(reconciled.slots.reduce(
    (sum, s) => sum + (s.endMin - s.startMin) / 60, 0,
  ));
  const finalApprovable = round2(reconciled.slots.reduce(
    (sum, s) => forecastKinds.has(s.source.kind)
      ? sum + (s.endMin - s.startMin) / 60
      : sum,
    0,
  ));

  const summary: NormalizationSummary = {
    raw_total_hours: round2(rawTotal),
    normalized_total_hours: round2(normalizedTotal),
    hours_removed_for_unavailability: reconciled.hours_removed_for_unavailability,
    hours_removed_for_duplicates: reconciled.hours_removed_for_duplicates,
    hours_removed_for_operating_hours: windowed.hoursRemoved,
    hours_removed_for_minimum_shift: minimumLength.hoursRemoved,
    hours_changed_by_validation: round2(hoursChanged),
    intervals_auto_corrected: normalized.filter(n => n.validation_status === 'auto_corrected').length,
    intervals_needing_review: normalized.filter(n => n.validation_status === 'needs_review').length,
    intervals_rejected: normalized.filter(n => n.validation_status === 'rejected_or_unusable').length,
    total_normalized_timeline_hours: totalTimelineHours,
    final_approvable_hours: finalApprovable,
  };

  const report: ValidationReportRow[] = normalized.map(n => ({
    provider: n.providerName ?? input.identity.name ?? null,
    submission_id: n.submissionId ?? null,
    date: n.date ?? null,
    day_of_week: n.dayOfWeek ?? null,
    raw_time_range: `${n.raw_start_time}–${n.raw_end_time}`,
    corrected_time_range: `${n.normalized_start_time}–${n.normalized_end_time}`,
    raw_duration: n.original_duration_hours,
    corrected_duration: n.normalized_duration_hours,
    warnings: n.validation_warnings,
    correction_reason: n.correction_reason,
    used_in_forecast: n.used_in_forecast,
    needs_manual_review: n.needs_manual_review,
    validation_status: n.validation_status,
  }));

  // Detect aggregate violations and append to summary report as synthetic rows
  const dailyHours = new Map<string, number>();
  for (const s of reconciled.slots) {
    dailyHours.set(s.date, (dailyHours.get(s.date) ?? 0) + (s.endMin - s.startMin) / 60);
  }
  let daysOver = 0;
  for (const [, h] of dailyHours) if (h > config.max_daily_hours) daysOver++;
  const weeklyMax = Math.max(0, ...weeklyTotals(dailyHours));
  if (weeklyMax > config.max_weekly_hours) {
    report.push(syntheticReport(
      input.identity,
      `Weekly hours exceed threshold: max week=${weeklyMax.toFixed(1)}h > ${config.max_weekly_hours}h`,
    ));
  }
  if (daysOver > 0) {
    report.push(syntheticReport(
      input.identity,
      `${daysOver} day(s) exceed max_daily_hours=${config.max_daily_hours}h`,
    ));
  }

  return {
    identity: input.identity,
    targetMonth: input.targetMonth,
    normalized,
    timeline: reconciled.slots,
    outOfHoursTimeline: windowed.droppedSlots,
    policyCutTimeline: minimumLength.droppedSlots,
    summary,
    report,
    override_used: override,
  };
}

function weeklyTotals(dailyHours: Map<string, number>): number[] {
  const buckets = new Map<string, number>();
  for (const [date, h] of dailyHours) {
    const d = new Date(date + 'T00:00:00Z');
    if (isNaN(d.getTime())) continue;
    // ISO week start (Monday)
    const day = d.getUTCDay();
    const diff = (day + 6) % 7;
    d.setUTCDate(d.getUTCDate() - diff);
    const key = d.toISOString().slice(0, 10);
    buckets.set(key, (buckets.get(key) ?? 0) + h);
  }
  return Array.from(buckets.values());
}

function syntheticReport(identity: ProviderIdentity, message: string): ValidationReportRow {
  return {
    provider: identity.name ?? null,
    submission_id: null,
    date: null,
    day_of_week: null,
    raw_time_range: '',
    corrected_time_range: '',
    raw_duration: null,
    corrected_duration: null,
    warnings: [message],
    correction_reason: null,
    used_in_forecast: false,
    needs_manual_review: true,
    validation_status: 'needs_review',
  };
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
// === supabase/functions/_shared/submissionTimeline.ts ===
/**
 * Shared pipeline that turns a group of `schedule_submissions` rows
 * (provider + target_month) into:
 *   - the canonical normalized slot timeline (post override / AM-PM
 *     correction, dedup, unavailable subtraction)
 *   - a forecast-only sub-timeline (telehealth kinds by default)
 *   - a deterministic set of shift_recommendations rows
 *
 * Both `evaluate-schedule-submissions` and `emit-shift-recommendations`
 * MUST call this module so the two stages produce the exact same slots
 * and shift rec rows. Drift between them previously caused decisions to
 * cite hours that didn't match what was emitted to Homebase.
 *
 * IMPORTANT: This file is mirrored at
 *   supabase/functions/_shared/submissionTimeline.ts
 * for Deno edge-function consumption. Keep the two in sync.
 */

/** Shape of `schedule_submissions.parsed_shifts` produced by sync-jotform-submissions. */
export interface ParsedShiftsBlob {
  recurring_virtual?: unknown;
  one_off_virtual?: unknown;
  in_home_clinic?: unknown;
  unavailable_dates?: unknown;
  email?: string;
  [k: string]: unknown;
}

export interface SubmissionRow {
  id: string;
  submitted_at: string;
  parsed_shifts: ParsedShiftsBlob | null;
}

/**
 * Default kinds counted toward `final_approvable_hours`. In-home/clinic
 * shifts are staffed under a separate scope and capacity model, so they
 * do not consume telehealth demand-hour gaps. Override via
 * `forecastKinds` when the caller knows otherwise.
 */
export const TELEHEALTH_FORECAST_KINDS: IntervalKind[] = ['recurring', 'one_off'];

export type ShiftType = 'virtual_recurring' | 'virtual_oneoff' | 'in_home_clinic';

export const LONG_SHIFT_BREAK_POLICY = 'mandatory_1_hour_break_for_12h_shift';
export const PROVIDER_MEETING_BLACKOUT_WINDOW =
  '2026-06-24T12:00:00-05:00/2026-06-24T13:00:00-05:00';
const LONG_SHIFT_BREAK_MINUTES = 60;
const LONG_SHIFT_BREAK_THRESHOLD_MINUTES = 12 * 60;
const PROVIDER_MEETING_BLACKOUT_DATE = '2026-06-24';
const PROVIDER_MEETING_BLACKOUT_START_MIN = 12 * 60;
const PROVIDER_MEETING_BLACKOUT_END_MIN = 13 * 60;
const PROVIDER_MEETING_BLACKOUT_REASON =
  'Monthly provider meeting; do not schedule providers during this hour.';
const LONG_SHIFT_BREAK_REASON =
  'Provider submitted 12-hour availability; system added a required 1-hour break.';

export type SchedulingAdjustmentType = 'long_shift_break' | 'provider_meeting_blackout';

export interface SchedulingAdjustment {
  type: SchedulingAdjustmentType;
  date: string;
  originalStartMin: number;
  originalEndMin: number;
  startMin: number;
  endMin: number;
  hoursRemoved: number;
  reason: string;
  policy?: string;
  blackoutWindow?: string;
  originalShiftHours?: number;
  scheduledHoursAfterBreak?: number;
}

export interface SchedulingAdjustmentSummary {
  all: SchedulingAdjustment[];
  longShiftBreaks: SchedulingAdjustment[];
  providerMeetingBlackouts: SchedulingAdjustment[];
  hours_removed_for_long_shift_breaks: number;
  hours_removed_for_provider_meeting_blackouts: number;
}

type AdjustedSlot = ExpandedSlot & {
  schedulingAdjustments?: SchedulingAdjustment[];
};

export interface ShiftRecommendationRow {
  submission_id: string;
  provider_id: string;
  provider_name: string;
  target_month: string;
  shift_date: string;
  start_min: number;
  end_min: number;
  hours: number;
  shift_type: ShiftType;
  assigned_state: string | null;
  recommendation: 'publish' | 'cut';
  recommendation_reason: string;
  decision_run_id: string;
  publish_status: 'pending';
}

export interface BuildTimelineOptions {
  forecastKinds?: IntervalKind[];
  config?: ValidationConfig;
}

export interface BuildTimelineResult extends NormalizationResult {
  summary: NormalizationResult['summary'] & {
    hours_removed_for_long_shift_breaks: number;
    hours_removed_for_provider_meeting_blackouts: number;
  };
  /** Subset of `timeline` filtered by forecastKinds (default = telehealth). */
  forecastTimeline: ExpandedSlot[];
  /** Subset of `outOfHoursTimeline` filtered by forecastKinds. In-home /
   *  clinic shifts are not subject to the operating-hours window so they
   *  never appear here. */
  forecastOutOfHoursTimeline: ExpandedSlot[];
  /** Subset of `policyCutTimeline` filtered by forecastKinds. */
  forecastPolicyCutTimeline: ExpandedSlot[];
  /** Mandatory scheduling-layer removals applied after availability validation. */
  schedulingAdjustments: SchedulingAdjustmentSummary;
}

/**
 * Run a group of submissions through the validation/normalization pipeline.
 * Both consumers must use this so the timelines match.
 */
export function buildSubmissionTimeline(
  submissions: SubmissionRow[],
  identity: ProviderIdentity,
  targetMonth: string,
  options: BuildTimelineOptions = {},
): BuildTimelineResult {
  const forecastKinds = options.forecastKinds ?? TELEHEALTH_FORECAST_KINDS;

  // Sort chronologically (later wins on overlap inside the validator).
  const ordered = [...submissions].sort((a, b) =>
    a.submitted_at.localeCompare(b.submitted_at),
  );

  const unavailableDates = collectUnavailableDates(ordered);

  const input: NormalizationInput = {
    identity,
    submissions: ordered.map(s => ({
      submissionId: s.id,
      submittedAt: s.submitted_at,
      intervals: extractRawIntervalsFromParsedShifts(s.parsed_shifts),
    })),
    targetMonth,
    unavailableDates,
    forecastKinds,
    config: options.config,
  };

  const forecastSet = new Set(forecastKinds);
  const result = normalizeProviderAvailability(input);
  const adjusted = applySchedulingRules(result.timeline);
  const summary = {
    ...result.summary,
    total_normalized_timeline_hours: round2(sumHours(adjusted.timeline)),
    final_approvable_hours: round2(adjusted.timeline.reduce(
      (sum, s) => forecastSet.has(s.source.kind)
        ? sum + (s.endMin - s.startMin) / 60
        : sum,
      0,
    )),
    hours_removed_for_long_shift_breaks:
      adjusted.summary.hours_removed_for_long_shift_breaks,
    hours_removed_for_provider_meeting_blackouts:
      adjusted.summary.hours_removed_for_provider_meeting_blackouts,
  };
  const forecastTimeline = adjusted.timeline.filter(s => forecastSet.has(s.source.kind));
  const forecastOutOfHoursTimeline = result.outOfHoursTimeline.filter(s =>
    forecastSet.has(s.source.kind),
  );
  const forecastPolicyCutTimeline = result.policyCutTimeline.filter(s =>
    forecastSet.has(s.source.kind),
  );
  return {
    ...result,
    timeline: adjusted.timeline,
    summary,
    forecastTimeline,
    forecastOutOfHoursTimeline,
    forecastPolicyCutTimeline,
    schedulingAdjustments: adjusted.summary,
  };
}

export function extractRawIntervalsFromParsedShifts(parsed: ParsedShiftsBlob | null): RawInterval[] {
  if (!parsed) return [];
  const out: RawInterval[] = [];
  for (const e of parseWidgetArray(parsed.recurring_virtual)) {
    if (!e['Start Time (ET)'] || !e['End Time (ET)']) continue;
    out.push({
      kind: 'recurring',
      dayOfWeek: e['Day of Week'],
      rawStart: e['Start Time (ET)'],
      rawEnd: e['End Time (ET)'],
    });
  }
  for (const e of parseWidgetArray(parsed.one_off_virtual)) {
    const date = parseFormDate(e['Date']);
    if (!date || !e['Start Time (ET)'] || !e['End Time (ET)']) continue;
    out.push({
      kind: 'one_off',
      date,
      rawStart: e['Start Time (ET)'],
      rawEnd: e['End Time (ET)'],
    });
  }
  for (const e of parseWidgetArray(parsed.in_home_clinic)) {
    const date = parseFormDate(e['Date']);
    if (!date || !e['Start Time (ET)'] || !e['End Time (ET)']) continue;
    out.push({
      kind: 'in_home',
      date,
      rawStart: e['Start Time (ET)'],
      rawEnd: e['End Time (ET)'],
    });
  }
  return out;
}

export function emailFromParsedShifts(parsed: ParsedShiftsBlob | null): string | null {
  if (!parsed) return null;
  const e = parsed.email;
  return typeof e === 'string' && e.trim() ? e.trim() : null;
}

export function collectUnavailableDates(submissions: SubmissionRow[]): string[] {
  // We take the union of all listed unavailable dates across submissions in
  // the group: a provider who lists 6/15 off in their first submission and
  // forgets to re-list it in a resubmission still shouldn't be scheduled
  // there. ClinOps confirmed this is the desired behavior.
  //
  // The Jotform "When will you be unavailable to work?" widget stores rows
  // with `Start Date` / `End Date` columns and supports inclusive date
  // ranges (e.g. 06-06-2026 → 06-08-2026 means three off days). We expand
  // each range and also accept a single `Date` value as a fallback for any
  // legacy entry shape.
  const out = new Set<string>();
  for (const sub of submissions) {
    const parsed = sub.parsed_shifts;
    if (!parsed) continue;
    for (const e of parseWidgetArray(parsed.unavailable_dates)) {
      const start = parseFormDate(e['Start Date'] ?? e['Date']);
      const end = parseFormDate(e['End Date']) ?? start;
      if (!start) continue;
      for (const d of expandDateRange(start, end ?? start)) out.add(d);
    }
  }
  return Array.from(out);
}

export function parseAllocationsFromNotes(notes: string): Array<{ state: string; hours: number }> {
  const allocStr = notes.match(/alloc=([^;]+)/);
  if (!allocStr) return [];
  const out: Array<{ state: string; hours: number }> = [];
  const re = /([A-Z]{2}):([0-9.]+)h/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(allocStr[1])) !== null) {
    const hours = Number(m[2]);
    if (Number.isFinite(hours) && hours > 0) out.push({ state: m[1], hours });
  }
  return out;
}

export interface BuildShiftRecommendationsArgs {
  providerId: string;
  providerName: string;
  targetMonth: string;
  /** Full normalized timeline (all kinds). */
  timeline: ExpandedSlot[];
  /** Subset of timeline that participates in forecast cut budget. */
  forecastTimeline: ExpandedSlot[];
  /** Forecast slots protected from monthly oversupply trims. */
  protectedForecastTimeline?: ExpandedSlot[];
  /** Out-of-business-hours fragments (telehealth only). Each is emitted as
   *  its own `cut` row with reason "outside operating hours". They are
   *  not part of the forecast cut budget — they were already removed from
   *  `final_approvable_hours` upstream. */
  outOfHoursTimeline?: ExpandedSlot[];
  /** Policy-rejected fragments, e.g. MH blocks shorter than 2.5h. */
  policyCutTimeline?: ExpandedSlot[];
  policyCutReason?: string;
  unallocatedForecastPublishReason?: string;
  declinedHours: number;
  /** True if the entire forecast timeline should be cut (declined decision). */
  declineAll: boolean;
  allocations: Array<{ state: string; hours: number }>;
  decisionRunId: string;
}

const OUT_OF_HOURS_REASON =
  'Cut — outside operating hours window (9a–9p ET weekdays, 9a–12p ET weekends)';
const POLICY_CUT_REASON = 'Cut — below minimum shift length policy';

const FRIDAY_SCARCE_START_MIN = 12 * 60;

export function scarceCoverageWindowForSlot(slot: Pick<ExpandedSlot, 'date' | 'endMin'>): string | null {
  const day = dayOfWeekUtc(slot.date);
  if (day === 0) return 'sunday';
  if (day === 6) return 'saturday';
  if (day === 5 && slot.endMin > FRIDAY_SCARCE_START_MIN) return 'friday_pm';
  return null;
}

export function isScarceCoverageSlot(slot: Pick<ExpandedSlot, 'date' | 'endMin'>): boolean {
  return scarceCoverageWindowForSlot(slot) !== null;
}

function dayOfWeekUtc(dateIso: string): number {
  const [y, m, d] = dateIso.split('-').map(Number);
  return new Date(Date.UTC(y, m - 1, d)).getUTCDay();
}

/**
 * Cut/publish row generator shared by evaluator and emitter.
 *
 * Forecast slots (recurring_virtual / virtual_oneoff) participate in the
 * cut budget: latest-first, cut until `declinedHours` is satisfied. Partial
 * cut budgets split a block into publish/cut fragments instead of rounding up
 * to the whole block. Protected forecast slots are skipped by monthly
 * oversupply trims, which lets the evaluator preserve scarce coverage windows
 * before cutting less useful hours. In-home/clinic slots are not in the
 * forecast scope, so they are always `publish` and don't consume the cut
 * budget.
 *
 * Out-of-hours fragments (passed via `outOfHoursTimeline`) are emitted as
 * their own `cut` rows so the workbench surfaces hours declined for being
 * outside business hours alongside other cuts.
 */
export function buildShiftRecommendationRows(args: BuildShiftRecommendationsArgs): ShiftRecommendationRow[] {
  const outOfHours = args.outOfHoursTimeline ?? [];
  const policyCuts = args.policyCutTimeline ?? [];
  if (args.timeline.length === 0 && outOfHours.length === 0 && policyCuts.length === 0) return [];

  const forecastSlots = new Set(args.forecastTimeline);
  const protectedForecastSlots = new Set(args.protectedForecastTimeline ?? []);
  const cutBudgetTotal = args.declineAll
    ? sumHours(args.forecastTimeline)
    : Math.max(0, args.declinedHours);

  // Walk forecast slots latest-first to allocate cuts. For partial trims,
  // protected slots are skipped so scarce coverage windows survive the cut.
  const cutCandidates = args.declineAll
    ? args.forecastTimeline
    : args.forecastTimeline.filter(slot => !protectedForecastSlots.has(slot));
  const sortedDesc = [...cutCandidates].sort((a, b) =>
    b.date.localeCompare(a.date) || b.startMin - a.startMin,
  );
  const cutTailMinutes = new Map<ExpandedSlot, number>();
  let remainingCutMinutes = Math.max(0, Math.round(cutBudgetTotal * 60));
  for (const slot of sortedDesc) {
    if (remainingCutMinutes <= 0) break;
    const slotMinutes = Math.max(0, slot.endMin - slot.startMin);
    const cutMinutes = Math.min(slotMinutes, remainingCutMinutes);
    if (cutMinutes > 0) {
      cutTailMinutes.set(slot, cutMinutes);
      remainingCutMinutes -= cutMinutes;
    }
  }

  // Buckets for state assignment, only consumed by published forecast slots.
  const buckets = new Map<string, number>(args.allocations.map(a => [a.state, a.hours]));

  const makeRow = (
    slot: ExpandedSlot,
    startMin: number,
    endMin: number,
    recommendation: 'publish' | 'cut',
    assignedState: string | null,
    reason: string,
  ): ShiftRecommendationRow => ({
    submission_id: slot.source.submissionId ?? '',
    provider_id: args.providerId,
    provider_name: args.providerName,
    target_month: args.targetMonth,
    shift_date: slot.date,
    start_min: startMin,
    end_min: endMin,
    hours: round2((endMin - startMin) / 60),
    shift_type: kindToShiftType(slot.source.kind),
    assigned_state: assignedState,
    recommendation,
    recommendation_reason: appendSchedulingAdjustmentReasons(reason, slot),
    decision_run_id: args.decisionRunId,
    publish_status: 'pending',
  });

  const bestBucket = () => {
    let bestState: string | null = null;
    let bestRemaining = 0;
    for (const [state, remaining] of buckets) {
      if (remaining > bestRemaining) {
        bestState = state;
        bestRemaining = remaining;
      }
    }
    return { state: bestState, remaining: bestRemaining };
  };

  const publishForecastSegment = (
    slot: ExpandedSlot,
    startMin: number,
    endMin: number,
    isProtected: boolean,
  ): ShiftRecommendationRow[] => {
    const rows: ShiftRecommendationRow[] = [];
    let cursor = startMin;
    while (cursor < endMin) {
      const segmentMinutes = endMin - cursor;
      const { state, remaining } = bestBucket();
      if (!state || remaining <= 0.001) {
        if (args.allocations.length === 0 && args.unallocatedForecastPublishReason) {
          rows.push(makeRow(slot, cursor, endMin, 'publish', null, args.unallocatedForecastPublishReason));
          break;
        }
        const reason = isProtected
          ? (args.unallocatedForecastPublishReason ?? 'Publish (scarce coverage window; no state allocation, review manually)')
          : 'Split block and trimmed as state-specific surplus — no remaining state allocation';
        rows.push(makeRow(slot, cursor, endMin, isProtected ? 'publish' : 'cut', isProtected ? null : null, reason));
        break;
      }

      const remainingMinutes = Math.max(0, Math.round(remaining * 60));
      const publishMinutes = Math.min(segmentMinutes, remainingMinutes);
      if (publishMinutes <= 0) {
        rows.push(makeRow(
          slot,
          cursor,
          endMin,
          isProtected ? 'publish' : 'cut',
          isProtected ? state : null,
          isProtected
            ? `Publish to ${state} (scarce coverage window protected before monthly demand trim)`
            : 'Split block and trimmed as state-specific surplus — no remaining state allocation',
        ));
        break;
      }

      const next = cursor + publishMinutes;
      const splitSuffix = next < endMin ? '; split block to avoid state surplus' : '';
      const reason = isProtected
        ? `Publish to ${state} (scarce coverage window protected before monthly demand trim${splitSuffix})`
        : `Publish to ${state} (largest remaining state gap at time of allocation${splitSuffix})`;
      rows.push(makeRow(slot, cursor, next, 'publish', state, reason));
      buckets.set(state, round2(remaining - publishMinutes / 60));
      cursor = next;
    }
    return rows;
  };

  const timelineRows = args.timeline.flatMap(slot => {
    const isForecastSlot = forecastSlots.has(slot);
    const isProtected = isForecastSlot && protectedForecastSlots.has(slot);

    if (!isForecastSlot) {
      return [
        makeRow(
          slot,
          slot.startMin,
          slot.endMin,
          'publish',
          null,
          'Publish (in-home/clinic — not part of telehealth forecast scope)',
        ),
      ];
    }

    const cutMinutes = cutTailMinutes.get(slot) ?? 0;
    const publishEndMin = Math.max(slot.startMin, slot.endMin - cutMinutes);
    const rows: ShiftRecommendationRow[] = [];

    if (publishEndMin > slot.startMin) {
      rows.push(...publishForecastSegment(slot, slot.startMin, publishEndMin, isProtected));
    }
    if (cutMinutes > 0) {
      const reason = args.declineAll
        ? 'Declined — no demand-hour gap remained in any licensed state when allocator processed this provider'
        : 'Trimmed as oversupply — accepted hours capped at network demand';
      rows.push(makeRow(slot, publishEndMin, slot.endMin, 'cut', null, reason));
    }
    return rows;
  });

  const outOfHoursRows: ShiftRecommendationRow[] = outOfHours.map(slot => ({
    submission_id: slot.source.submissionId ?? '',
    provider_id: args.providerId,
    provider_name: args.providerName,
    target_month: args.targetMonth,
    shift_date: slot.date,
    start_min: slot.startMin,
    end_min: slot.endMin,
    hours: round2((slot.endMin - slot.startMin) / 60),
    shift_type: kindToShiftType(slot.source.kind),
    assigned_state: null,
    recommendation: 'cut',
    recommendation_reason: OUT_OF_HOURS_REASON,
    decision_run_id: args.decisionRunId,
    publish_status: 'pending',
  }));

  const policyCutRows: ShiftRecommendationRow[] = policyCuts.map(slot => ({
    submission_id: slot.source.submissionId ?? '',
    provider_id: args.providerId,
    provider_name: args.providerName,
    target_month: args.targetMonth,
    shift_date: slot.date,
    start_min: slot.startMin,
    end_min: slot.endMin,
    hours: round2((slot.endMin - slot.startMin) / 60),
    shift_type: kindToShiftType(slot.source.kind),
    assigned_state: null,
    recommendation: 'cut',
    recommendation_reason: args.policyCutReason ?? POLICY_CUT_REASON,
    decision_run_id: args.decisionRunId,
    publish_status: 'pending',
  }));

  return [...timelineRows, ...outOfHoursRows, ...policyCutRows].sort((a, b) =>
    a.shift_date.localeCompare(b.shift_date) || a.start_min - b.start_min,
  );
}

export function kindToShiftType(kind: IntervalKind): ShiftType {
  if (kind === 'recurring') return 'virtual_recurring';
  if (kind === 'in_home') return 'in_home_clinic';
  return 'virtual_oneoff';
}

function applySchedulingRules(slots: ExpandedSlot[]): {
  timeline: ExpandedSlot[];
  summary: SchedulingAdjustmentSummary;
} {
  const longShiftBreaks: SchedulingAdjustment[] = [];
  const providerMeetingBlackouts: SchedulingAdjustment[] = [];
  const out: AdjustedSlot[] = [];

  for (const slot of slots) {
    const blackoutAdjusted = applyProviderMeetingBlackout(slot);
    if (blackoutAdjusted.adjustment) {
      providerMeetingBlackouts.push(blackoutAdjusted.adjustment);
    }

    for (const blackoutSlot of blackoutAdjusted.slots) {
      const breakAdjusted = applyLongShiftBreak(blackoutSlot);
      if (breakAdjusted.adjustment) {
        longShiftBreaks.push(breakAdjusted.adjustment);
      }
      out.push(...breakAdjusted.slots);
    }
  }

  const all = [...longShiftBreaks, ...providerMeetingBlackouts].sort((a, b) =>
    a.date.localeCompare(b.date) ||
    a.startMin - b.startMin ||
    a.endMin - b.endMin ||
    a.type.localeCompare(b.type),
  );

  return {
    timeline: out.sort((a, b) =>
      a.date.localeCompare(b.date) ||
      a.startMin - b.startMin ||
      a.endMin - b.endMin,
    ),
    summary: {
      all,
      longShiftBreaks,
      providerMeetingBlackouts,
      hours_removed_for_long_shift_breaks: round2(sumAdjustmentHours(longShiftBreaks)),
      hours_removed_for_provider_meeting_blackouts: round2(sumAdjustmentHours(providerMeetingBlackouts)),
    },
  };
}

function applyProviderMeetingBlackout(slot: ExpandedSlot): {
  slots: AdjustedSlot[];
  adjustment: SchedulingAdjustment | null;
} {
  if (slot.date !== PROVIDER_MEETING_BLACKOUT_DATE) {
    return { slots: [slot as AdjustedSlot], adjustment: null };
  }
  const overlapStart = Math.max(slot.startMin, PROVIDER_MEETING_BLACKOUT_START_MIN);
  const overlapEnd = Math.min(slot.endMin, PROVIDER_MEETING_BLACKOUT_END_MIN);
  if (overlapEnd <= overlapStart) {
    return { slots: [slot as AdjustedSlot], adjustment: null };
  }

  const adjustment: SchedulingAdjustment = {
    type: 'provider_meeting_blackout',
    date: slot.date,
    originalStartMin: slot.startMin,
    originalEndMin: slot.endMin,
    startMin: overlapStart,
    endMin: overlapEnd,
    hoursRemoved: round2((overlapEnd - overlapStart) / 60),
    reason: PROVIDER_MEETING_BLACKOUT_REASON,
    blackoutWindow: PROVIDER_MEETING_BLACKOUT_WINDOW,
  };

  const parts: AdjustedSlot[] = [];
  if (slot.startMin < overlapStart) {
    parts.push(withSchedulingAdjustment({ ...slot, endMin: overlapStart }, adjustment));
  }
  if (overlapEnd < slot.endMin) {
    parts.push(withSchedulingAdjustment({ ...slot, startMin: overlapEnd }, adjustment));
  }

  return { slots: parts, adjustment };
}

function applyLongShiftBreak(slot: ExpandedSlot): {
  slots: AdjustedSlot[];
  adjustment: SchedulingAdjustment | null;
} {
  const durationMin = slot.endMin - slot.startMin;
  if (durationMin < LONG_SHIFT_BREAK_THRESHOLD_MINUTES) {
    return { slots: [slot as AdjustedSlot], adjustment: null };
  }

  const firstWorkMinutes = Math.floor(((durationMin - LONG_SHIFT_BREAK_MINUTES) / 2) / 30) * 30;
  const breakStart = slot.startMin + firstWorkMinutes;
  const breakEnd = breakStart + LONG_SHIFT_BREAK_MINUTES;
  const adjustment: SchedulingAdjustment = {
    type: 'long_shift_break',
    date: slot.date,
    originalStartMin: slot.startMin,
    originalEndMin: slot.endMin,
    startMin: breakStart,
    endMin: breakEnd,
    hoursRemoved: 1,
    reason: LONG_SHIFT_BREAK_REASON,
    policy: LONG_SHIFT_BREAK_POLICY,
    originalShiftHours: round2(durationMin / 60),
    scheduledHoursAfterBreak: round2((durationMin - LONG_SHIFT_BREAK_MINUTES) / 60),
  };

  const slots: AdjustedSlot[] = [];
  if (slot.startMin < breakStart) {
    slots.push(withSchedulingAdjustment({ ...slot, endMin: breakStart }, adjustment));
  }
  if (breakEnd < slot.endMin) {
    slots.push(withSchedulingAdjustment({ ...slot, startMin: breakEnd }, adjustment));
  }

  return { slots, adjustment };
}

function withSchedulingAdjustment(slot: ExpandedSlot, adjustment: SchedulingAdjustment): AdjustedSlot {
  const prior = (slot as AdjustedSlot).schedulingAdjustments ?? [];
  return { ...slot, schedulingAdjustments: [...prior, adjustment] };
}

function appendSchedulingAdjustmentReasons(reason: string, slot: ExpandedSlot): string {
  const additions = schedulingAdjustmentReasonLines(slot);
  if (additions.length === 0) return reason;
  return [reason, ...additions].join('; ');
}

function schedulingAdjustmentReasonLines(slot: ExpandedSlot): string[] {
  const adjustments = (slot as AdjustedSlot).schedulingAdjustments ?? [];
  const lines: string[] = [];
  for (const adjustment of adjustments) {
    if (adjustment.type === 'long_shift_break') {
      lines.push(
        `Mandatory 1-hour break applied (${formatClock24(adjustment.startMin)}-${formatClock24(adjustment.endMin)} ET); ` +
        `${adjustment.scheduledHoursAfterBreak ?? 11} schedulable hours from the original ${adjustment.originalShiftHours ?? 12}-hour block`,
      );
    } else if (adjustment.type === 'provider_meeting_blackout') {
      lines.push(
        `Provider meeting blackout removed ${formatClock24(adjustment.startMin)}-${formatClock24(adjustment.endMin)} ET`,
      );
    }
  }
  return Array.from(new Set(lines));
}

// ─── Local widget helpers ────────────────────────────────────────────────

function parseWidgetArray(raw: unknown): Record<string, string>[] {
  if (raw == null) return [];
  let parsed: unknown = raw;
  if (typeof raw === 'string') {
    try { parsed = JSON.parse(raw); } catch { return []; }
  }
  if (!Array.isArray(parsed)) return [];
  return parsed.filter((e): e is Record<string, string> => e != null && typeof e === 'object');
}

function parseFormDate(raw: unknown): string | null {
  if (!raw) return null;
  const s = String(raw).trim();
  const mdy = s.match(/^(\d{1,2})-(\d{1,2})-(\d{4})$/);
  if (mdy) return `${mdy[3]}-${mdy[1].padStart(2, '0')}-${mdy[2].padStart(2, '0')}`;
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
  return null;
}

function expandDateRange(startISO: string, endISO: string): string[] {
  // Inclusive expansion in UTC to avoid DST drift.
  const [sy, sm, sd] = startISO.split('-').map(Number);
  const [ey, em, ed] = endISO.split('-').map(Number);
  let cur = Date.UTC(sy, sm - 1, sd);
  const last = Date.UTC(ey, em - 1, ed);
  if (!Number.isFinite(cur) || !Number.isFinite(last) || last < cur) {
    return [startISO];
  }
  const out: string[] = [];
  const DAY = 86_400_000;
  while (cur <= last) {
    const d = new Date(cur);
    out.push(
      `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`,
    );
    cur += DAY;
  }
  return out;
}

function sumHours(slots: ExpandedSlot[]): number {
  return slots.reduce((s, x) => s + (x.endMin - x.startMin) / 60, 0);
}

function sumAdjustmentHours(adjustments: SchedulingAdjustment[]): number {
  return adjustments.reduce((sum, adjustment) => sum + adjustment.hoursRemoved, 0);
}

function formatClock24(totalMinutes: number): string {
  const h = Math.floor(totalMinutes / 60);
  const m = totalMinutes % 60;
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
// === supabase/functions/_shared/providerPriority.ts ===
export type ProviderPriorityKey =
  | 'clinical_supervisor'
  | 'vitable_internal'
  | 'directshifts_brittany_priority'
  | 'access_provider';

export type ProviderPriority = {
  key: ProviderPriorityKey;
  rank: 0 | 1 | 2;
  label: string;
};

export type ProviderPriorityProfile = {
  name?: string | null;
  profession?: string | null;
  employment_type?: string | null;
  source?: string | null;
  shift_types?: string[] | null;
  hourly_rate?: number | string | null;
  utilization_pct?: number | string | null;
};

export const PROVIDER_PRIORITY_BY_KEY: Record<ProviderPriorityKey, ProviderPriority> = {
  clinical_supervisor: { key: 'clinical_supervisor', rank: 0, label: 'Clinical supervisor' },
  vitable_internal: { key: 'vitable_internal', rank: 1, label: 'Rate-ranked Vitable provider' },
  directshifts_brittany_priority: {
    key: 'directshifts_brittany_priority',
    rank: 1,
    label: 'Rate-ranked DirectShifts Brittney Afram',
  },
  access_provider: { key: 'access_provider', rank: 1, label: 'Rate-ranked access provider' },
};

const DEFAULT_PROVIDER_PRIORITY = PROVIDER_PRIORITY_BY_KEY.vitable_internal;

const normalizedProviderText = (profile: ProviderPriorityProfile | null | undefined) => {
  if (!profile) return '';
  const employmentType = (profile.employment_type ?? '').trim().toLowerCase();
  const source = (profile.source ?? '').trim().toLowerCase();
  const shiftTypes = Array.isArray(profile.shift_types) ? profile.shift_types : [];
  return [
    profile.name,
    profile.profession,
    employmentType,
    source,
    ...shiftTypes,
  ]
    .filter(Boolean)
    .join(' ')
    .toLowerCase()
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
};

function isBrittneyAframName(profile: ProviderPriorityProfile | null | undefined): boolean {
  const name = (profile?.name ?? '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  const tokens = new Set(name.split(/\s+/).filter(Boolean));
  return tokens.has('afram') && (tokens.has('brittney') || tokens.has('brittany'));
}

export function isDirectShiftsProvider(profile: ProviderPriorityProfile | null | undefined): boolean {
  if (!profile) return false;
  const employmentType = (profile.employment_type ?? '').trim().toLowerCase();
  const source = (profile.source ?? '').trim().toLowerCase();
  const haystack = normalizedProviderText(profile);
  return (
    employmentType === 'agency' ||
    source.includes('directshifts') ||
    source.includes('direct shifts') ||
    haystack.includes('directshifts') ||
    haystack.includes('direct shifts') ||
    haystack.includes('agency supplied') ||
    isBrittneyAframName(profile)
  );
}

export function isBrittneyAframDirectShiftsProvider(
  profile: ProviderPriorityProfile | null | undefined,
): boolean {
  return isBrittneyAframName(profile) && isDirectShiftsProvider(profile);
}

export function providerPriorityFor(
  profile: ProviderPriorityProfile | null | undefined,
): ProviderPriority {
  if (!profile) return DEFAULT_PROVIDER_PRIORITY;
  const employmentType = (profile.employment_type ?? '').trim().toLowerCase();
  const source = (profile.source ?? '').trim().toLowerCase();
  const haystack = normalizedProviderText(profile);

  if (
    haystack.includes('clinical supervisor') ||
    haystack.includes('clinical lead') ||
    haystack.includes('supervisor')
  ) {
    return PROVIDER_PRIORITY_BY_KEY.clinical_supervisor;
  }

  if (isBrittneyAframDirectShiftsProvider(profile)) {
    return PROVIDER_PRIORITY_BY_KEY.directshifts_brittany_priority;
  }

  if (
    employmentType === 'agency' ||
    source.includes('directshifts') ||
    source.includes('direct shifts') ||
    source.includes('access') ||
    haystack.includes('directshifts') ||
    haystack.includes('direct shifts') ||
    haystack.includes('access provider') ||
    haystack.includes('agency supplied')
  ) {
    return PROVIDER_PRIORITY_BY_KEY.access_provider;
  }

  return DEFAULT_PROVIDER_PRIORITY;
}

export function providerHourlyRate(profile: ProviderPriorityProfile | null | undefined): number | null {
  const raw = profile?.hourly_rate;
  if (raw === null || raw === undefined || raw === '') return null;
  const n = typeof raw === 'number' ? raw : Number(String(raw).replace(/[$,]/g, ''));
  return Number.isFinite(n) && n >= 0 ? n : null;
}

export function providerUtilizationPct(
  profile: ProviderPriorityProfile | null | undefined,
): number | null {
  const raw = profile?.utilization_pct;
  if (raw === null || raw === undefined || raw === '') return null;
  const n = typeof raw === 'number' ? raw : Number(String(raw).replace(/[%,$]/g, ''));
  return Number.isFinite(n) && n >= 0 ? n : null;
}

export function compareProviderAllocationPriority(
  a: ProviderPriorityProfile | null | undefined,
  b: ProviderPriorityProfile | null | undefined,
): number {
  const priorityA = providerPriorityFor(a);
  const priorityB = providerPriorityFor(b);
  if (priorityA.rank !== priorityB.rank) return priorityA.rank - priorityB.rank;

  const rateA = providerHourlyRate(a);
  const rateB = providerHourlyRate(b);
  const rateSortA = rateA ?? Number.POSITIVE_INFINITY;
  const rateSortB = rateB ?? Number.POSITIVE_INFINITY;
  if (rateSortA !== rateSortB) return rateSortA - rateSortB;

  const utilizationA = providerUtilizationPct(a);
  const utilizationB = providerUtilizationPct(b);
  const utilizationSortA = utilizationA ?? Number.POSITIVE_INFINITY;
  const utilizationSortB = utilizationB ?? Number.POSITIVE_INFINITY;
  if (utilizationSortA !== utilizationSortB) return utilizationSortA - utilizationSortB;

  const bothDirectShifts = isDirectShiftsProvider(a) && isDirectShiftsProvider(b);
  if (bothDirectShifts) {
    const brittneyAframRankA = isBrittneyAframDirectShiftsProvider(a) ? 0 : 1;
    const brittneyAframRankB = isBrittneyAframDirectShiftsProvider(b) ? 0 : 1;
    if (brittneyAframRankA !== brittneyAframRankB) return brittneyAframRankA - brittneyAframRankB;
  }

  return 0;
}
// === supabase/functions/emit-shift-recommendations/index.ts ===
/**
 * emit-shift-recommendations edge function
 *
 * Reads post-decision schedule_submissions and writes per-shift
 * publish/cut rows into shift_recommendations. The output is what the
 * scheduling team uses to enter shifts into Homebase.
 *
 * Runs after evaluate-schedule-submissions has set decision_status,
 * accepted_hours, declined_hours and a decision_notes string that
 * includes "alloc=ST:Hh,..." for the per-state allocations.
 *
 * Timeline parity: this function uses the same shared
 * `buildSubmissionTimeline` / `buildShiftRecommendationRows` helpers as
 * the evaluator. Given the same submissions, the two functions produce
 * the exact same set of slots (and therefore shift rec rows) — guaranteed
 * by tests in availabilityValidation.test.ts.
 *
 * Modes:
 *   POST /functions/v1/emit-shift-recommendations?target_month=YYYY-MM-01
 *   POST /functions/v1/emit-shift-recommendations?provider_id=<uuid>
 *   POST /functions/v1/emit-shift-recommendations
 *     -> all current+future-month submissions with a decision
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const MH_COACHING_PROFESSIONS = new Set([
  'MENTAL_HEALTH_COACH',
  'MH_COACH',
  'HEALTH_COACH',
]);
const THERAPY_PROFESSIONS = new Set([
  'LPC',
  'LCSW',
  'LICSW',
  'LMFT',
  'MFT',
  'LMHC',
  'THERAPIST',
  'LICENSED_CLINICAL_SOCIAL_WORKER',
  'LICENSED_PROFESSIONAL_COUNSELOR',
]);
const MENTAL_HEALTH_PROVIDER_OVERRIDES = new Map<string, 'mh_coaching' | 'therapy'>([
  ['matthew vazquez', 'mh_coaching'],
  ['matthew vasquez', 'mh_coaching'],
  ['jamie fuentes', 'mh_coaching'],
  ['jennifer yost', 'mh_coaching'],
  ['esha shah', 'mh_coaching'],
  ['liana griebsch', 'mh_coaching'],
  ['li griebsch', 'mh_coaching'],
  ['li greibsch', 'mh_coaching'],
  ['michelle diederich', 'mh_coaching'],
  ['margaret margo mulgrew', 'therapy'],
  ['margaret mulgrew', 'therapy'],
  ['margo mulgrew', 'therapy'],
  ['richard travis rash', 'therapy'],
  ['richard rash', 'therapy'],
  ['mishelle lockerby', 'therapy'],
  ['mishelle lockerby direct shifts', 'therapy'],
]);
const normProfession = (profession: string | null | undefined) =>
  (profession ?? '')
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
const normProviderName = (name: string | null | undefined) =>
  (name ?? '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
const isMentalHealthProvider = (
  profession: string | null | undefined,
  ...providerNames: Array<string | null | undefined>
) => {
  for (const providerName of providerNames) {
    if (MENTAL_HEALTH_PROVIDER_OVERRIDES.has(normProviderName(providerName))) return true;
  }
  const norm = normProfession(profession);
  return MH_COACHING_PROFESSIONS.has(norm) || THERAPY_PROFESSIONS.has(norm);
};

const MH_MIN_SHIFT_HOURS = 2.5;
const MENTAL_HEALTH_VALIDATION_CONFIG = {
  ...DEFAULT_VALIDATION_CONFIG,
  min_single_shift_hours: MH_MIN_SHIFT_HOURS,
};
const MH_POLICY_CUT_REASON =
  'Cut — mental health shifts must be at least 2.5h (3 visits at 40m plus charting buffers; EHR slots stay back-to-back)';
const MH_PUBLISH_REASON =
  'Publish (mental health service-line forecast; state allocator bypassed)';

const shiftKey = (r: {
  submission_id: string;
  shift_date: string;
  start_min: number;
  end_min: number;
  shift_type: string;
}) =>
  `${r.submission_id}|${r.shift_date}|${r.start_min}|${r.end_min}|${r.shift_type}`;

function assertUniqueShiftRecommendationRows(rows: ShiftRecommendationRow[]) {
  const seen = new Set<string>();
  for (const row of rows) {
    const key = shiftKey(row);
    if (seen.has(key)) {
      throw new Error(`duplicate shift_recommendations row generated for ${key}`);
    }
    seen.add(key);
  }
}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

type Submission = {
  id: string;
  provider_id: string | null;
  provider_name: string;
  target_month: string;
  parsed_shifts: ParsedShiftsBlob | null;
  decision_status: string;
  accepted_hours: number | null;
  declined_hours: number | null;
  decision_notes: string | null;
  submitted_at: string;
  decision_run_id: string | null;
};

type ProviderProfile = {
  id: string;
  name: string | null;
  profession: string | null;
};

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  const url = new URL(req.url);
  const monthFilter = url.searchParams.get('target_month');
  const providerFilter = url.searchParams.get('provider_id');

  const counters = {
    groups: 0,
    rows_inserted: 0,
    rows_deleted: 0,
    skipped_no_decision: 0,
    skipped_needs_review: 0,
    errors: 0,
  };
  const errors: Array<{ submission_id: string; error: string }> = [];

  try {
    let q = supabase
      .from('schedule_submissions')
      .select('id, provider_id, provider_name, target_month, parsed_shifts, decision_status, accepted_hours, declined_hours, decision_notes, submitted_at, decision_run_id');

    if (monthFilter) q = q.eq('target_month', monthFilter);
    if (providerFilter) q = q.eq('provider_id', providerFilter);
    // We only emit recommendations for groups with a real allocator decision.
    // 'needs_review' rows are intentionally excluded — they require human
    // intervention before any shift can be published.
    q = q.in('decision_status', ['accepted', 'partial', 'declined']);
    q = q.range(0, 49999);

    const { data, error } = await q;
    if (error) throw new Error(`submissions load: ${error.message}`);

    const subs = (data ?? []) as Submission[];

    const groups = new Map<string, Submission[]>();
    for (const s of subs) {
      if (!s.provider_id) continue;
      const k = `${s.provider_id}|${s.target_month}`;
      if (!groups.has(k)) groups.set(k, []);
      groups.get(k)!.push(s);
    }

    // Need every submission in the group (including superseded) to rebuild
    // the timeline correctly — superseded rows still contributed slots.
    const providerMonths = Array.from(groups.keys());
    if (providerMonths.length > 0) {
      const providerIds = Array.from(new Set(providerMonths.map(k => k.split('|')[0])));
      const months = Array.from(new Set(providerMonths.map(k => k.split('|')[1])));
      const { data: peers, error: pErr } = await supabase
        .from('schedule_submissions')
        .select('id, provider_id, provider_name, target_month, parsed_shifts, decision_status, accepted_hours, declined_hours, decision_notes, submitted_at, decision_run_id')
        .in('provider_id', providerIds)
        .in('target_month', months)
        .eq('decision_status', 'superseded')
        .range(0, 49999);
      if (pErr) throw new Error(`peer load: ${pErr.message}`);
      for (const s of (peers ?? []) as Submission[]) {
        if (!s.provider_id) continue;
        const k = `${s.provider_id}|${s.target_month}`;
        if (groups.has(k)) groups.get(k)!.push(s);
      }
    }

    const providerIdsForEmit = Array.from(new Set(
      Array.from(groups.keys()).map(k => k.split('|')[0]),
    ));
    const providerProfileByProvider = new Map<string, ProviderProfile>();
    if (providerIdsForEmit.length > 0) {
      const { data: providers, error: provErr } = await supabase
        .from('providers')
        .select('id, name, profession')
        .in('id', providerIdsForEmit);
      if (provErr) throw new Error(`provider load: ${provErr.message}`);
      for (const provider of (providers ?? []) as ProviderProfile[]) {
        providerProfileByProvider.set(provider.id, provider);
      }
    }

    for (const [key, groupSubs] of groups) {
      try {
        counters.groups++;
        const decided = groupSubs
          .filter(s => s.decision_status !== 'superseded')
          .sort((a, b) => b.submitted_at.localeCompare(a.submitted_at))[0];
        if (!decided) {
          counters.skipped_no_decision++;
          continue;
        }
        if (decided.decision_status === 'needs_review') {
          counters.skipped_needs_review++;
          continue;
        }
        const providerProfile = providerProfileByProvider.get(decided.provider_id!);
        const isMentalHealth =
          isMentalHealthProvider(
            providerProfile?.profession,
            providerProfile?.name,
            decided.provider_name,
          ) ||
          (decided.decision_notes ?? '').includes('mental_health_bypass');

        const ids = groupSubs.map(s => s.id);
        const { count: deletedCount, error: dErr } = await supabase
          .from('shift_recommendations')
          .delete({ count: 'exact' })
          .in('submission_id', ids);
        if (dErr) throw new Error(`delete prior: ${dErr.message}`);
        counters.rows_deleted += deletedCount ?? 0;

        // Build the canonical timeline using the same shared pipeline that
        // the evaluator used. Inputs (submissions, identity, target_month)
        // produce identical timelines on both sides.
        const validation = buildSubmissionTimeline(
          groupSubs.map(s => ({
            id: s.id,
            submitted_at: s.submitted_at,
            parsed_shifts: s.parsed_shifts ?? null,
          })),
          {
            providerId: decided.provider_id,
            email: emailFromParsedShifts(decided.parsed_shifts),
            name: decided.provider_name,
          },
          decided.target_month,
          isMentalHealth ? { config: MENTAL_HEALTH_VALIDATION_CONFIG } : {},
        );

        if (
          validation.timeline.length === 0 &&
          validation.forecastOutOfHoursTimeline.length === 0 &&
          validation.forecastPolicyCutTimeline.length === 0
        ) continue;

        const declined = Number(decided.declined_hours ?? 0);
        const allocations = parseAllocationsFromNotes(decided.decision_notes ?? '');
        // declined_hours stored on the row includes forecast cuts plus
        // policy cuts (outside operating hours, MH minimum-shift failures).
        // Policy cuts are re-emitted from their dedicated timelines, so we
        // subtract them here to leave only the forecast cut budget.
        const oohHours = Math.round((validation.summary.hours_removed_for_operating_hours ?? 0) * 100) / 100;
        const policyHours = Math.round((validation.summary.hours_removed_for_minimum_shift ?? 0) * 100) / 100;
        const forecastDeclined = Math.max(0, Math.round((declined - oohHours - policyHours) * 100) / 100);
        const protectScarceWindows = (decided.decision_notes ?? '')
          .includes('scarce_window_policy=protected_before_monthly_trim');
        const protectedForecastTimeline = protectScarceWindows
          ? validation.forecastTimeline.filter(isScarceCoverageSlot)
          : [];

        const rows = buildShiftRecommendationRows({
          providerId: decided.provider_id!,
          providerName: decided.provider_name,
          targetMonth: decided.target_month,
          timeline: validation.timeline,
          forecastTimeline: validation.forecastTimeline,
          outOfHoursTimeline: validation.forecastOutOfHoursTimeline,
          policyCutTimeline: validation.forecastPolicyCutTimeline,
          policyCutReason: isMentalHealth ? MH_POLICY_CUT_REASON : undefined,
          unallocatedForecastPublishReason: isMentalHealth ? MH_PUBLISH_REASON : undefined,
          protectedForecastTimeline,
          declinedHours: forecastDeclined,
          declineAll: decided.decision_status === 'declined',
          allocations,
          decisionRunId: decided.decision_run_id ?? crypto.randomUUID(),
        });
        assertUniqueShiftRecommendationRows(rows);

        const CHUNK = 500;
        for (let i = 0; i < rows.length; i += CHUNK) {
          const chunk = rows.slice(i, i + CHUNK);
          const { error: iErr } = await supabase.from('shift_recommendations').insert(chunk);
          if (iErr) throw new Error(`insert: ${iErr.message}`);
          counters.rows_inserted += chunk.length;
        }
      } catch (e) {
        counters.errors++;
        const msg = e instanceof Error ? e.message : String(e);
        errors.push({ submission_id: key, error: msg });
        console.error('group failed', key, msg);
      }
    }

    return json({ ok: true, ...counters, errors });
  } catch (err) {
    return json({ error: err instanceof Error ? err.message : String(err), ...counters }, 500);
  }
});

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}
