// AUTOGENERATED — do not edit by hand.
// Source: see supabase/functions/<name>/index.ts and supabase/functions/_shared/*.ts
// Regenerate with: ./scripts/bundle-edge-function.sh <entrypoint>
// This file is committed so the deployed edge function code is byte-reproducible
// from the repo even when shipping via the Supabase MCP single-file path.

// === supabase/functions/_shared/nameNormalization.ts ===
/** Deno-compatible copy of src/lib/nameNormalization.ts */

const CREDENTIAL_PATTERN =
  /\b(md|do|np|aprn|pa-c|pa|rn|bsn|msn|dnp|phd|fnp|fnp-c|fnp-bc|agacnp|agpcnp|pmhnp|crna|cnm|dnp-c|lcsw|lpc|mft|psyd)\b\.?/gi;

const SUFFIX_PATTERN = /\b(jr\.?|sr\.?|ii|iii|iv)\b\.?/gi;

const COMMA_LAST_FIRST = /^([^,]+),\s*(.+)$/;

export function canonicalName(raw: string | null | undefined): string {
  if (!raw) return '';
  let s = raw.trim();

  const commaMatch = COMMA_LAST_FIRST.exec(s);
  if (commaMatch) s = `${commaMatch[2].trim()} ${commaMatch[1].trim()}`;

  s = s.replace(CREDENTIAL_PATTERN, ' ');
  s = s.replace(SUFFIX_PATTERN, ' ');
  s = s.replace(/^dr\.?\s+/i, '');

  const parts = s.toLowerCase().replace(/[^a-z\s]/g, ' ').split(/\s+/).filter(Boolean);

  if (parts.length >= 3) {
    return `${parts[0]} ${parts[parts.length - 1]}`;
  }
  return parts.join(' ');
}

function jaccardBigrams(a: string, b: string): number {
  if (!a || !b) return 0;
  const bigrams = (s: string) => {
    const set = new Set<string>();
    for (let i = 0; i < s.length - 1; i++) set.add(s.slice(i, i + 2));
    return set;
  };
  const setA = bigrams(a);
  const setB = bigrams(b);
  const intersection = [...setA].filter(x => setB.has(x)).length;
  const union = new Set([...setA, ...setB]).size;
  return union === 0 ? 0 : intersection / union;
}

function levenshtein(a: string, b: string): number {
  const m = a.length, n = b.length;
  const dp: number[][] = Array.from({ length: m + 1 }, (_, i) =>
    Array.from({ length: n + 1 }, (_, j) => (i === 0 ? j : j === 0 ? i : 0))
  );
  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      dp[i][j] = a[i - 1] === b[j - 1]
        ? dp[i - 1][j - 1]
        : 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]);
    }
  }
  return dp[m][n];
}

export function fuzzyScore(a: string, b: string): number {
  const ca = canonicalName(a);
  const cb = canonicalName(b);
  if (!ca || !cb) return 0;
  if (ca === cb) return 1;
  const jaccard = jaccardBigrams(ca, cb);
  const maxLen = Math.max(ca.length, cb.length);
  const lev = maxLen === 0 ? 1 : 1 - levenshtein(ca, cb) / maxLen;
  return 0.6 * jaccard + 0.4 * lev;
}

export const FUZZY_MATCH_THRESHOLD = 0.85;
// === supabase/functions/_shared/availabilityOverrides.ts ===
/** Deno-compatible copy of src/config/availabilityOverrides.ts.
 *  Keep in sync with the canonical version. */

export interface ValidationConfig {
  /** Reject any single shift longer than this (after correction). */
  max_single_shift_hours: number;
  /** Flag if a single calendar date totals more than this. */
  max_daily_hours: number;
  /** Flag if any ISO week totals more than this. */
  max_weekly_hours: number;
  /** If false, end <= start is treated as an error (not a midnight crossing). */
  allow_overnight_shifts: boolean;
  /** Surface a warning when start is exactly 12:00 AM. */
  flag_midnight_start: boolean;
  /** Surface a warning when a recurring window covers ~the entire day. */
  flag_full_day_availability: boolean;
  /** Operating-hours window in minutes from midnight (ET). Shifts outside the
   *  window are clamped (partial overlap) or cut entirely (no overlap).
   *  Tracked in `hours_removed_for_operating_hours`. */
  weekday_window_start_min: number;
  weekday_window_end_min: number;
  weekend_window_start_min: number;
  weekend_window_end_min: number;
}

export const DEFAULT_VALIDATION_CONFIG: ValidationConfig = {
  max_single_shift_hours: 12,
  max_daily_hours: 12,
  max_weekly_hours: 60,
  allow_overnight_shifts: false,
  flag_midnight_start: true,
  flag_full_day_availability: true,
  // 9:00 AM - 9:00 PM ET on weekdays, 9:00 AM - 12:00 PM ET on weekends.
  weekday_window_start_min: 540,
  weekday_window_end_min: 1260,
  weekend_window_start_min: 540,
  weekend_window_end_min: 720,
};

export interface ProviderOverrideRule {
  /** Optional: only match this kind of interval. */
  kind?: 'recurring' | 'one_off' | 'in_home';
  /** Optional: only match this weekday (case-insensitive). */
  dayOfWeek?: string;
  /** Raw start/end as the provider entered them on the Jotform widget. */
  rawStart: string;
  rawEnd: string;
  /** Corrected start/end. */
  normalizedStart: string;
  normalizedEnd: string;
  /** Free-form note explaining the correction (shows up in the audit log). */
  reason?: string;
}

export interface ProviderOverride {
  /** Display name — included for human readability in logs. */
  fullName?: string;
  /** Most stable matcher; preferred. */
  email?: string;
  /** Provider UUID, if known. */
  providerId?: string;
  rules: ProviderOverrideRule[];
}

/**
 * Default overrides keyed off ClinOps's May 2026 audit of bad submissions.
 * Add new entries here rather than encoding fixes inside the validator.
 */
export const AVAILABILITY_OVERRIDES: ProviderOverride[] = [
  {
    fullName: 'Cassondra Hawkins',
    rules: [
      {
        kind: 'recurring',
        dayOfWeek: 'Friday',
        rawStart: '4:00 AM',
        rawEnd: '9:00 PM',
        normalizedStart: '4:00 PM',
        normalizedEnd: '9:00 PM',
        reason: 'Cassondra Hawkins Friday: confirmed afternoon-only availability; 4 AM is an AM/PM entry error',
      },
      {
        kind: 'recurring',
        dayOfWeek: 'Sunday',
        rawStart: '9:00 AM',
        rawEnd: '12:00 AM',
        normalizedStart: '9:00 AM',
        normalizedEnd: '12:00 PM',
        reason: 'Cassondra Hawkins Sunday: confirmed morning-only availability; 12 AM end is an AM/PM entry error',
      },
    ],
  },
  {
    fullName: 'Akosua Norgbey',
    rules: [
      {
        rawStart: '8:00 AM',
        rawEnd: '11:59 PM',
        normalizedStart: '8:00 AM',
        normalizedEnd: '12:00 PM',
        reason: 'Akosua Norgbey: confirmed morning-only window; do not credit full-day capacity',
      },
    ],
  },
  {
    fullName: 'Melissa Harris-Perotti',
    rules: [
      {
        rawStart: '12:00 AM',
        rawEnd: '6:00 PM',
        normalizedStart: '12:00 PM',
        normalizedEnd: '6:00 PM',
        reason: 'Melissa Harris-Perotti: confirmed afternoon-only availability; 12 AM start is an AM/PM entry error',
      },
    ],
  },
  {
    fullName: 'Shadae McMillan',
    rules: [
      {
        rawStart: '12:00 AM',
        rawEnd: '3:00 PM',
        normalizedStart: '12:00 PM',
        normalizedEnd: '3:00 PM',
        reason: 'Shadae McMillan: confirmed afternoon-only availability; 12 AM start is an AM/PM entry error',
      },
    ],
  },
];
// === supabase/functions/_shared/availabilityValidation.ts ===
/** Deno-compatible copy of src/lib/availabilityValidation.ts.
 *
 * Keep in sync with the canonical version. Edge functions
 * (sync-jotform-submissions, evaluate-schedule-submissions) import from here. */

export type ValidationStatus =
  | 'valid'
  | 'auto_corrected'
  | 'needs_review'
  | 'rejected_or_unusable';

export type CorrectionConfidence = 'high' | 'medium' | 'low' | 'none';

export type IntervalKind = 'recurring' | 'one_off' | 'in_home';

/** Input to validation; comes from the parsed Jotform widget. */
export interface RawInterval {
  kind: IntervalKind;
  /** Recurring entries identify a weekday (e.g. "Monday"). */
  dayOfWeek?: string;
  /** One-off and in-home entries identify a calendar date (YYYY-MM-DD). */
  date?: string;
  /** Raw "09:00 AM" / "5:00 PM" / "13:00" strings as submitted. */
  rawStart: string;
  rawEnd: string;
  /** Submission ID, for audit linkage. */
  submissionId?: string;
  /** Provider display name, for the report. */
  providerName?: string;
}

export interface NormalizedInterval {
  kind: IntervalKind;
  dayOfWeek?: string;
  date?: string;
  raw_start_time: string;
  raw_end_time: string;
  /** "HH:MM AM/PM" canonical form of the corrected start. */
  normalized_start_time: string;
  normalized_end_time: string;
  original_duration_hours: number | null;
  normalized_duration_hours: number | null;
  validation_status: ValidationStatus;
  validation_warnings: string[];
  correction_reason: string | null;
  correction_confidence: CorrectionConfidence;
  /** Whether the evaluator should use this interval when allocating demand. */
  used_in_forecast: boolean;
  needs_manual_review: boolean;
  submissionId?: string;
  providerName?: string;
  /** Internal: corrected time as minutes from midnight, for downstream merge. */
  normalized_start_min: number | null;
  normalized_end_min: number | null;
}

export interface ProviderIdentity {
  providerId?: string | null;
  email?: string | null;
  name?: string | null;
}

export interface NormalizationSummary {
  raw_total_hours: number;
  normalized_total_hours: number;
  hours_removed_for_unavailability: number;
  hours_removed_for_duplicates: number;
  /** Hours dropped or trimmed because the slot fell outside the configured
   *  operating-hours window (default 9 AM - 9 PM ET weekdays, 9 AM - 12 PM ET
   *  weekends). */
  hours_removed_for_operating_hours: number;
  hours_changed_by_validation: number;
  intervals_auto_corrected: number;
  intervals_needing_review: number;
  intervals_rejected: number;
  /** Sum of timeline slots across ALL kinds (telehealth + in-home/clinic). */
  total_normalized_timeline_hours: number;
  /** Sum of timeline slots restricted to forecastKinds (default telehealth-only). */
  final_approvable_hours: number;
}

export interface ValidationReportRow {
  provider: string | null;
  submission_id: string | null;
  date: string | null;
  day_of_week: string | null;
  raw_time_range: string;
  corrected_time_range: string;
  raw_duration: number | null;
  corrected_duration: number | null;
  warnings: string[];
  correction_reason: string | null;
  used_in_forecast: boolean;
  needs_manual_review: boolean;
  validation_status: ValidationStatus;
}

// ─── Time parsing & formatting ────────────────────────────────────────────

interface ParsedTime {
  /** Minutes from midnight, 0..1440. 24:00 stays as 1440 only when input was 24:00. */
  totalMinutes: number;
  hour: number;
  minute: number;
  ampm: 'AM' | 'PM' | null;
}

/** Parses "09:00 AM", "5:00 PM", "13:00", "11:59 PM" → ParsedTime. */
export function parseTimeOfDay(raw: string | null | undefined): ParsedTime | null {
  if (raw == null) return null;
  const m = String(raw).trim().match(/^(\d{1,2}):(\d{2})\s*(AM|PM)?\s*$/i);
  if (!m) return null;
  let h = Number(m[1]);
  const min = Number(m[2]);
  const ampmRaw = (m[3] ?? '').toUpperCase();
  const ampm: 'AM' | 'PM' | null = ampmRaw === 'AM' ? 'AM' : ampmRaw === 'PM' ? 'PM' : null;
  if (ampm === 'AM') {
    if (h === 12) h = 0;
  } else if (ampm === 'PM') {
    if (h !== 12) h += 12;
  }
  if (h < 0 || h > 24 || min < 0 || min >= 60) return null;
  return { totalMinutes: h * 60 + min, hour: h, minute: min, ampm };
}

/** Format minutes-from-midnight as "h:mm AM/PM" canonical string. */
export function formatTime(totalMinutes: number): string {
  const safe = ((totalMinutes % 1440) + 1440) % 1440;
  const h24 = Math.floor(safe / 60);
  const m = safe % 60;
  const ampm = h24 < 12 ? 'AM' : 'PM';
  let h12 = h24 % 12;
  if (h12 === 0) h12 = 12;
  return `${h12}:${String(m).padStart(2, '0')} ${ampm}`;
}

/** Difference end - start, treating end <= start as overnight (+24h). */
export function intervalHours(startMin: number, endMin: number): number {
  let diff = endMin - startMin;
  if (diff <= 0) diff += 24 * 60;
  return diff / 60;
}

// ─── Override matching ────────────────────────────────────────────────────

/**
 * Resolve a provider's override rules using the most stable identifier
 * available: email first (most stable), then provider UUID, then a
 * canonicalized full name match. Returns null if no override exists.
 */
export function findProviderOverride(
  identity: ProviderIdentity,
  overrides: ProviderOverride[] = AVAILABILITY_OVERRIDES,
): ProviderOverride | null {
  const email = (identity.email ?? '').trim().toLowerCase();
  if (email) {
    const byEmail = overrides.find(o => (o.email ?? '').toLowerCase() === email);
    if (byEmail) return byEmail;
  }
  if (identity.providerId) {
    const byId = overrides.find(o => o.providerId === identity.providerId);
    if (byId) return byId;
  }
  const canon = canonicalName(identity.name ?? '');
  if (canon) {
    const byName = overrides.find(o => canonicalName(o.fullName ?? '') === canon);
    if (byName) return byName;
  }
  return null;
}

/**
 * Attempt to match a raw interval against one of a provider's override
 * rules. Match keys: rawStart + rawEnd, plus optional dayOfWeek and kind.
 */
function matchOverrideRule(
  raw: RawInterval,
  override: ProviderOverride | null,
): ProviderOverrideRule | null {
  if (!override) return null;
  const rawStartNorm = canonicalTimeKey(raw.rawStart);
  const rawEndNorm = canonicalTimeKey(raw.rawEnd);
  for (const rule of override.rules) {
    const ruleStart = canonicalTimeKey(rule.rawStart);
    const ruleEnd = canonicalTimeKey(rule.rawEnd);
    if (ruleStart !== rawStartNorm || ruleEnd !== rawEndNorm) continue;
    if (rule.kind && rule.kind !== raw.kind) continue;
    if (rule.dayOfWeek && (raw.dayOfWeek ?? '').toLowerCase() !== rule.dayOfWeek.toLowerCase()) {
      continue;
    }
    return rule;
  }
  return null;
}

function canonicalTimeKey(t: string | undefined | null): string {
  const p = parseTimeOfDay(t ?? '');
  if (!p) return String(t ?? '').trim().toLowerCase();
  return formatTime(p.totalMinutes).toLowerCase();
}

// ─── Per-interval validation ──────────────────────────────────────────────

interface DefaultCorrectionResult {
  correctedStartMin: number;
  correctedEndMin: number;
  reason: string;
  confidence: CorrectionConfidence;
}

/**
 * Apply built-in deterministic AM/PM corrections that don't need a
 * provider-specific override. These are intentionally conservative:
 * each rule combines a pattern in the raw entry with an additional
 * implausibility signal (oversize duration or full-day recurring) so
 * we don't silently rewrite legitimate shifts.
 */
function applyDefaultCorrection(
  raw: RawInterval,
  startMin: number,
  endMin: number,
  config: ValidationConfig,
): DefaultCorrectionResult | null {
  const rawDuration = intervalHours(startMin, endMin);

  // Rule: 12:00 AM start with afternoon/evening end → start was meant as 12 PM.
  // Examples: 12:00 AM–3:00 PM → 12:00 PM–3:00 PM; 12:00 AM–6:00 PM → 12:00 PM–6:00 PM.
  if (
    config.flag_midnight_start &&
    startMin === 0 &&
    endMin >= 12 * 60 + 1 && // anything past noon
    endMin <= 22 * 60 // sanity cap
  ) {
    return {
      correctedStartMin: 12 * 60,
      correctedEndMin: endMin,
      reason: '12:00 AM start with afternoon/evening end normalized to 12:00 PM (likely AM/PM entry error)',
      confidence: 'high',
    };
  }

  // Rule: very early AM start (1–5 AM) paired with evening end is almost
  // always an AM/PM error on the start. e.g. 4:00 AM–9:00 PM → 4:00 PM–9:00 PM.
  // Trigger only if the resulting raw shift would exceed the single-shift cap.
  if (
    startMin >= 60 && startMin < 5 * 60 &&
    endMin >= 17 * 60 &&
    rawDuration > config.max_single_shift_hours
  ) {
    return {
      correctedStartMin: startMin + 12 * 60,
      correctedEndMin: endMin,
      reason: `Early-AM start (${formatTime(startMin)}) with evening end exceeds ${config.max_single_shift_hours}h; normalized start to PM`,
      confidence: 'medium',
    };
  }

  // Rule: end at 12:00 AM with morning start almost always means 12:00 PM.
  // e.g. 9:00 AM–12:00 AM → 9:00 AM–12:00 PM. Only fires when overnight is
  // disallowed AND the overnight reading would exceed max_single_shift.
  if (
    !config.allow_overnight_shifts &&
    endMin === 0 &&
    startMin >= 6 * 60 && startMin <= 11 * 60
  ) {
    const overnightDuration = intervalHours(startMin, endMin); // wraps to next day
    if (overnightDuration > config.max_single_shift_hours) {
      return {
        correctedStartMin: startMin,
        correctedEndMin: 12 * 60,
        reason: `Morning start with 12:00 AM end would be ${overnightDuration.toFixed(1)}h overnight; normalized end to 12:00 PM`,
        confidence: 'medium',
      };
    }
  }

  return null;
}

/**
 * Validate and (if applicable) correct a single raw interval.
 *
 * Order of precedence:
 *   1. Provider-specific override rule (highest authority).
 *   2. Default deterministic AM/PM corrections.
 *   3. Otherwise: keep raw, but flag warnings.
 */
export function validateInterval(
  raw: RawInterval,
  config: ValidationConfig = DEFAULT_VALIDATION_CONFIG,
  override: ProviderOverride | null = null,
): NormalizedInterval {
  const warnings: string[] = [];
  const startParsed = parseTimeOfDay(raw.rawStart);
  const endParsed = parseTimeOfDay(raw.rawEnd);

  // Malformed times are unusable.
  if (!startParsed || !endParsed) {
    return buildNormalized(raw, {
      startMin: 0,
      endMin: 0,
      normalizedStartMin: null,
      normalizedEndMin: null,
      originalDuration: null,
      normalizedDuration: null,
      status: 'rejected_or_unusable',
      warnings: ['Malformed or unparseable time string'],
      reason: null,
      confidence: 'none',
      usedInForecast: false,
      needsReview: true,
    });
  }

  const startMin = startParsed.totalMinutes;
  const endMin = endParsed.totalMinutes;

  // Original duration: we treat end <= start as overnight here for the audit
  // value (so we report what the provider literally typed).
  const originalDuration = intervalHours(startMin, endMin);

  // 1) Provider-specific override
  const overrideRule = matchOverrideRule(raw, override);
  if (overrideRule) {
    const ovStart = parseTimeOfDay(overrideRule.normalizedStart);
    const ovEnd = parseTimeOfDay(overrideRule.normalizedEnd);
    if (ovStart && ovEnd) {
      const newDuration = intervalHours(ovStart.totalMinutes, ovEnd.totalMinutes);
      const status: ValidationStatus = 'auto_corrected';
      warnings.push(`Provider-specific override applied: ${overrideRule.reason ?? 'configured rule'}`);
      return buildNormalized(raw, {
        startMin,
        endMin,
        normalizedStartMin: ovStart.totalMinutes,
        normalizedEndMin: ovEnd.totalMinutes,
        originalDuration,
        normalizedDuration: newDuration,
        status,
        warnings,
        reason: `provider_override: ${overrideRule.reason ?? `${formatTime(startMin)}-${formatTime(endMin)} → ${formatTime(ovStart.totalMinutes)}-${formatTime(ovEnd.totalMinutes)}`}`,
        confidence: 'high',
      });
    }
  }

  // Detect "full-day recurring availability" before default correction so we
  // can flag it for review when no override mapped it to a real window.
  const isFullDayRecurring =
    raw.kind === 'recurring' &&
    config.flag_full_day_availability &&
    isFullDayWindow(startMin, endMin);

  if (isFullDayRecurring) {
    warnings.push('Recurring availability spans nearly the entire day (e.g. 8 AM–11:59 PM); flagged for review unless a provider-specific override is configured');
  }

  // 2) Default deterministic correction
  const defaultCorrection = applyDefaultCorrection(raw, startMin, endMin, config);
  if (defaultCorrection && !isFullDayRecurring) {
    const newDuration = intervalHours(defaultCorrection.correctedStartMin, defaultCorrection.correctedEndMin);
    warnings.push(defaultCorrection.reason);
    // Re-run sanity checks against the corrected window
    const correctedWarnings = collectShiftWarnings(
      defaultCorrection.correctedStartMin,
      defaultCorrection.correctedEndMin,
      config,
    );
    for (const w of correctedWarnings) warnings.push(`(post-correction) ${w}`);
    return buildNormalized(raw, {
      startMin,
      endMin,
      normalizedStartMin: defaultCorrection.correctedStartMin,
      normalizedEndMin: defaultCorrection.correctedEndMin,
      originalDuration,
      normalizedDuration: newDuration,
      status: 'auto_corrected',
      warnings,
      reason: defaultCorrection.reason,
      confidence: defaultCorrection.confidence,
    });
  }

  // 3) No correction — apply raw checks
  for (const w of collectShiftWarnings(startMin, endMin, config)) warnings.push(w);

  // End <= start: overnight handling
  let status: ValidationStatus = 'valid';
  const normalizedStartMin: number | null = startMin;
  const normalizedEndMin: number | null = endMin;
  const normalizedDuration: number | null = originalDuration;
  const reason: string | null = null;
  const confidence: CorrectionConfidence = 'none';
  let usedInForecast = true;
  let needsReview = false;

  if (endMin <= startMin) {
    if (config.allow_overnight_shifts) {
      warnings.push('Overnight shift accepted (allow_overnight_shifts=true)');
    } else {
      warnings.push('End time is at or before start time and overnight shifts are not allowed; flagged for review');
      status = 'needs_review';
      needsReview = true;
      usedInForecast = false;
    }
  }

  if (isFullDayRecurring) {
    status = 'needs_review';
    needsReview = true;
    usedInForecast = false;
  }

  if (originalDuration > config.max_single_shift_hours) {
    warnings.push(`Single shift duration ${originalDuration.toFixed(2)}h exceeds max_single_shift_hours=${config.max_single_shift_hours}h`);
    if (status === 'valid') {
      status = 'needs_review';
      needsReview = true;
      usedInForecast = false;
    }
  }

  return buildNormalized(raw, {
    startMin,
    endMin,
    normalizedStartMin,
    normalizedEndMin,
    originalDuration,
    normalizedDuration,
    status,
    warnings,
    reason,
    confidence,
    usedInForecast,
    needsReview,
  });
}

function isFullDayWindow(startMin: number, endMin: number): boolean {
  // Treat any window covering >= 14 hours within a single day starting before
  // 9 AM and ending at/after 23:30 as "full-day" for review-flag purposes.
  if (endMin <= startMin) return false;
  const dur = (endMin - startMin) / 60;
  return startMin <= 9 * 60 && endMin >= 23 * 60 + 30 && dur >= 14;
}

function collectShiftWarnings(startMin: number, endMin: number, config: ValidationConfig): string[] {
  const out: string[] = [];
  if (config.flag_midnight_start && startMin === 0 && endMin > 0 && endMin <= 22 * 60) {
    out.push('Start time is 12:00 AM with non-overnight end — likely AM/PM entry error');
  }
  if (config.flag_full_day_availability && isFullDayWindow(startMin, endMin)) {
    out.push('Window spans nearly the entire day');
  }
  return out;
}

interface BuildArgs {
  startMin: number;
  endMin: number;
  normalizedStartMin: number | null;
  normalizedEndMin: number | null;
  originalDuration: number | null;
  normalizedDuration: number | null;
  status: ValidationStatus;
  warnings: string[];
  reason: string | null;
  confidence: CorrectionConfidence;
  usedInForecast?: boolean;
  needsReview?: boolean;
}

function buildNormalized(raw: RawInterval, args: BuildArgs): NormalizedInterval {
  const usedInForecast =
    args.usedInForecast ??
    (args.status === 'valid' || args.status === 'auto_corrected');
  const needsReview =
    args.needsReview ?? args.status === 'needs_review';
  return {
    kind: raw.kind,
    dayOfWeek: raw.dayOfWeek,
    date: raw.date,
    raw_start_time: raw.rawStart,
    raw_end_time: raw.rawEnd,
    normalized_start_time:
      args.normalizedStartMin == null ? raw.rawStart : formatTime(args.normalizedStartMin),
    normalized_end_time:
      args.normalizedEndMin == null ? raw.rawEnd : formatTime(args.normalizedEndMin),
    original_duration_hours:
      args.originalDuration == null ? null : round2(args.originalDuration),
    normalized_duration_hours:
      args.normalizedDuration == null ? null : round2(args.normalizedDuration),
    validation_status: args.status,
    validation_warnings: args.warnings,
    correction_reason: args.reason,
    correction_confidence: args.confidence,
    used_in_forecast: usedInForecast,
    needs_manual_review: needsReview,
    submissionId: raw.submissionId,
    providerName: raw.providerName,
    normalized_start_min: args.normalizedStartMin,
    normalized_end_min: args.normalizedEndMin,
  };
}

// ─── Pipeline-level helpers ───────────────────────────────────────────────

/**
 * Date-level expansion of a normalized interval into one (date, startMin, endMin)
 * tuple per matching weekday in the target month, with overnight crossings split.
 * Returns an empty array for intervals not used in forecast.
 */
export interface ExpandedSlot {
  date: string; // YYYY-MM-DD
  startMin: number;
  endMin: number; // > startMin
  source: NormalizedInterval;
}

const DAY_TO_INDEX: Record<string, number> = {
  sunday: 0, monday: 1, tuesday: 2, wednesday: 3,
  thursday: 4, friday: 5, saturday: 6,
};

export function weekdayDatesInMonth(dayName: string, monthISO: string): string[] {
  const dayIdx = DAY_TO_INDEX[String(dayName).trim().toLowerCase()];
  if (dayIdx === undefined) return [];
  const [y, m] = monthISO.split('-').map(Number);
  const firstWeekday = new Date(Date.UTC(y, m - 1, 1)).getUTCDay();
  const daysInMonth = new Date(Date.UTC(y, m, 0)).getUTCDate();
  const offset = (dayIdx - firstWeekday + 7) % 7;
  const out: string[] = [];
  for (let day = 1 + offset; day <= daysInMonth; day += 7) {
    out.push(`${y}-${String(m).padStart(2, '0')}-${String(day).padStart(2, '0')}`);
  }
  return out;
}

export function nextDate(dateISO: string): string | null {
  const d = new Date(dateISO + 'T00:00:00Z');
  if (isNaN(d.getTime())) return null;
  d.setUTCDate(d.getUTCDate() + 1);
  return d.toISOString().slice(0, 10);
}

export function expandNormalizedToSlots(
  normalized: NormalizedInterval,
  targetMonth: string,
): ExpandedSlot[] {
  if (!normalized.used_in_forecast) return [];
  if (normalized.normalized_start_min == null || normalized.normalized_end_min == null) return [];
  const startMin = normalized.normalized_start_min;
  const endMin = normalized.normalized_end_min;

  const dates: string[] = [];
  if (normalized.kind === 'recurring' && normalized.dayOfWeek) {
    dates.push(...weekdayDatesInMonth(normalized.dayOfWeek, targetMonth));
  } else if (normalized.date) {
    if (isInMonth(normalized.date, targetMonth)) dates.push(normalized.date);
  }

  const slots: ExpandedSlot[] = [];
  for (const date of dates) {
    if (endMin <= startMin) {
      slots.push({ date, startMin, endMin: 1440, source: normalized });
      const next = nextDate(date);
      if (next && isInMonth(next, targetMonth)) {
        slots.push({ date: next, startMin: 0, endMin, source: normalized });
      }
    } else {
      slots.push({ date, startMin, endMin, source: normalized });
    }
  }
  return slots;
}

/** Apply the operating-hours window to a stream of expanded slots, clamping
 *  partial overlaps and dropping fully out-of-window slots. Returns the
 *  surviving slots (possibly clamped), the original portions that were
 *  dropped/trimmed (so downstream can emit per-shift "declined: outside
 *  business hours" rows), and the total hours removed. The source
 *  NormalizedInterval is preserved for downstream linkage; in-home /
 *  clinic shifts are NOT subject to this filter (their location is fixed
 *  outside the telehealth ops window). */
export function applyOperatingHoursWindow(
  slots: ExpandedSlot[],
  config: ValidationConfig,
): { slots: ExpandedSlot[]; droppedSlots: ExpandedSlot[]; hoursRemoved: number } {
  const out: ExpandedSlot[] = [];
  const dropped: ExpandedSlot[] = [];
  let removed = 0;
  for (const s of slots) {
    if (s.source.kind === 'in_home') {
      out.push(s);
      continue;
    }
    const d = new Date(s.date + 'T00:00:00Z');
    const dow = d.getUTCDay();
    const isWeekend = dow === 0 || dow === 6;
    const winStart = isWeekend ? config.weekend_window_start_min : config.weekday_window_start_min;
    const winEnd = isWeekend ? config.weekend_window_end_min : config.weekday_window_end_min;

    const rawHours = (s.endMin - s.startMin) / 60;
    if (s.endMin <= winStart || s.startMin >= winEnd) {
      removed += rawHours;
      dropped.push(s);
      continue;
    }
    const newStart = Math.max(s.startMin, winStart);
    const newEnd = Math.min(s.endMin, winEnd);
    if (newEnd <= newStart) {
      removed += rawHours;
      dropped.push(s);
      continue;
    }
    if (newStart === s.startMin && newEnd === s.endMin) {
      out.push(s);
    } else {
      removed += ((newStart - s.startMin) + (s.endMin - newEnd)) / 60;
      out.push({ ...s, startMin: newStart, endMin: newEnd });
      if (newStart > s.startMin) {
        dropped.push({ ...s, startMin: s.startMin, endMin: newStart });
      }
      if (newEnd < s.endMin) {
        dropped.push({ ...s, startMin: newEnd, endMin: s.endMin });
      }
    }
  }
  return { slots: out, droppedSlots: dropped, hoursRemoved: round2(removed) };
}

function isInMonth(dateISO: string, monthISO: string): boolean {
  return dateISO >= monthISO && dateISO < nextMonth(monthISO);
}

function nextMonth(monthISO: string): string {
  const [y, m] = monthISO.split('-').map(Number);
  const ny = m === 12 ? y + 1 : y;
  const nm = m === 12 ? 1 : m + 1;
  return `${ny}-${String(nm).padStart(2, '0')}-01`;
}

// ─── Dedup / merge / unavailable subtraction ──────────────────────────────

export interface ReconciledTimeline {
  /** One slot per (date, start, end) — duplicates collapsed, later submissions
   *  overwrite earlier overlapping slots. */
  slots: ExpandedSlot[];
  hours_removed_for_duplicates: number;
  hours_removed_for_unavailability: number;
  intervals_overlapping_unavailable: ExpandedSlot[];
}

export interface DatedSlotInput extends ExpandedSlot {
  submittedAt?: string; // ISO; later wins
}

/**
 * Merge a stream of expanded slots from one or more submissions for the same
 * provider+month. Behaviour:
 *   - Slots are processed chronologically by submittedAt.
 *   - When a new slot overlaps an existing slot on the same date, the new
 *     slot wins; the existing slot is trimmed or dropped.
 *   - Identical (date, start, end) duplicates collapse silently.
 *   - hours_removed_for_duplicates accumulates the hours that were dropped
 *     because a later slot covered them.
 *   - Unavailable dates passed in are subtracted AFTER merge.
 */
export function reconcileTimeline(
  inputs: DatedSlotInput[],
  unavailableDates: string[] = [],
): ReconciledTimeline {
  const sorted = [...inputs].sort((a, b) =>
    (a.submittedAt ?? '').localeCompare(b.submittedAt ?? '') ||
    a.date.localeCompare(b.date) ||
    a.startMin - b.startMin,
  );

  let timeline: ExpandedSlot[] = [];
  let dupHours = 0;

  for (const incoming of sorted) {
    const before = totalHours(timeline);
    timeline = mergeSlot(timeline, incoming);
    const after = totalHours(timeline);
    const incomingHours = (incoming.endMin - incoming.startMin) / 60;
    const delta = before + incomingHours - after; // positive = displaced existing
    if (delta > 0.001) dupHours += delta;
  }

  const unavailable = new Set(unavailableDates);
  let unavailHours = 0;
  const overlappingUnavailable: ExpandedSlot[] = [];
  const filtered: ExpandedSlot[] = [];
  for (const s of timeline) {
    if (unavailable.has(s.date)) {
      unavailHours += (s.endMin - s.startMin) / 60;
      overlappingUnavailable.push(s);
      continue;
    }
    filtered.push(s);
  }

  return {
    slots: filtered,
    hours_removed_for_duplicates: round2(dupHours),
    hours_removed_for_unavailability: round2(unavailHours),
    intervals_overlapping_unavailable: overlappingUnavailable,
  };
}

function mergeSlot(timeline: ExpandedSlot[], incoming: ExpandedSlot): ExpandedSlot[] {
  const out: ExpandedSlot[] = [];
  for (const existing of timeline) {
    if (existing.date !== incoming.date || !overlaps(existing, incoming)) {
      out.push(existing);
      continue;
    }
    if (existing.startMin < incoming.startMin) {
      out.push({ ...existing, endMin: incoming.startMin });
    }
    if (existing.endMin > incoming.endMin) {
      out.push({ ...existing, startMin: incoming.endMin });
    }
  }
  out.push(incoming);
  return out;
}

function overlaps(a: ExpandedSlot, b: ExpandedSlot): boolean {
  return a.startMin < b.endMin && b.startMin < a.endMin;
}

function totalHours(slots: ExpandedSlot[]): number {
  return slots.reduce((sum, s) => sum + (s.endMin - s.startMin) / 60, 0);
}

// ─── Top-level pipeline ───────────────────────────────────────────────────

export interface NormalizationInput {
  identity: ProviderIdentity;
  /** Each submission contributes intervals tagged with submittedAt. */
  submissions: Array<{
    submissionId: string;
    submittedAt: string; // ISO
    intervals: RawInterval[];
  }>;
  targetMonth: string; // YYYY-MM-01
  unavailableDates?: string[];
  config?: ValidationConfig;
  overrides?: ProviderOverride[];
  /**
   * Interval kinds that count toward `summary.final_approvable_hours`.
   * Default: ['recurring', 'one_off'] — i.e. telehealth only. In-home /
   * clinic shifts are scoped separately and do not consume telehealth
   * demand-hour gaps. Pass ['recurring','one_off','in_home'] to opt in.
   * The full normalized `timeline` always contains every kind so downstream
   * shift recommendations can still publish in-home shifts.
   */
  forecastKinds?: IntervalKind[];
}

export interface NormalizationResult {
  identity: ProviderIdentity;
  targetMonth: string;
  normalized: NormalizedInterval[];
  timeline: ExpandedSlot[];
  /** Original portions of slots that were dropped/trimmed by the operating-
   *  hours window (9a-9p ET weekdays, 9a-12p ET weekends). Each entry is
   *  the original out-of-window fragment with its source NormalizedInterval
   *  preserved, so downstream can emit "declined: outside business hours"
   *  per-shift rows. */
  outOfHoursTimeline: ExpandedSlot[];
  summary: NormalizationSummary;
  report: ValidationReportRow[];
  override_used: ProviderOverride | null;
}

/**
 * Full pipeline: validate → normalize → expand → reconcile (dedup/unavail) →
 * summarize. The slots/timeline output is what evaluate-schedule-submissions
 * should consume for forecast approve/deny — they reflect corrected times.
 */
export function normalizeProviderAvailability(input: NormalizationInput): NormalizationResult {
  const config = input.config ?? DEFAULT_VALIDATION_CONFIG;
  const overrides = input.overrides ?? AVAILABILITY_OVERRIDES;
  const override = findProviderOverride(input.identity, overrides);

  const normalized: NormalizedInterval[] = [];
  const slotInputs: DatedSlotInput[] = [];
  let rawTotal = 0;

  for (const sub of input.submissions) {
    for (const raw of sub.intervals) {
      const tagged: RawInterval = { ...raw, submissionId: sub.submissionId, providerName: input.identity.name ?? raw.providerName };
      const norm = validateInterval(tagged, config, override);
      normalized.push(norm);
      if (norm.original_duration_hours != null) rawTotal += norm.original_duration_hours;

      const slots = expandNormalizedToSlots(norm, input.targetMonth);
      for (const s of slots) slotInputs.push({ ...s, submittedAt: sub.submittedAt });

      // Out-of-month detection for one-off / in-home with explicit dates
      if ((norm.kind === 'one_off' || norm.kind === 'in_home') && norm.date) {
        if (!isInMonth(norm.date, input.targetMonth)) {
          norm.validation_warnings.push(`Date ${norm.date} is outside target month ${input.targetMonth}`);
          if (norm.validation_status === 'valid' || norm.validation_status === 'auto_corrected') {
            norm.validation_status = 'needs_review';
            norm.needs_manual_review = true;
            norm.used_in_forecast = false;
          }
        }
      }
    }
  }

  const windowed = applyOperatingHoursWindow(slotInputs, config);
  const windowedSlotInputs: DatedSlotInput[] = windowed.slots.map(s => {
    const orig = slotInputs.find(
      o => o.date === s.date && o.source === s.source,
    );
    return { ...s, submittedAt: orig?.submittedAt };
  });
  const reconciled = reconcileTimeline(windowedSlotInputs, input.unavailableDates ?? []);

  const normalizedTotal = normalized.reduce(
    (sum, n) => sum + (n.normalized_duration_hours ?? 0),
    0,
  );
  const hoursChanged = normalized.reduce((sum, n) => {
    if (n.normalized_duration_hours == null || n.original_duration_hours == null) return sum;
    return sum + Math.abs(n.normalized_duration_hours - n.original_duration_hours);
  }, 0);

  const forecastKinds = new Set<IntervalKind>(input.forecastKinds ?? ['recurring', 'one_off']);
  const totalTimelineHours = round2(reconciled.slots.reduce(
    (sum, s) => sum + (s.endMin - s.startMin) / 60, 0,
  ));
  const finalApprovable = round2(reconciled.slots.reduce(
    (sum, s) => forecastKinds.has(s.source.kind)
      ? sum + (s.endMin - s.startMin) / 60
      : sum,
    0,
  ));

  const summary: NormalizationSummary = {
    raw_total_hours: round2(rawTotal),
    normalized_total_hours: round2(normalizedTotal),
    hours_removed_for_unavailability: reconciled.hours_removed_for_unavailability,
    hours_removed_for_duplicates: reconciled.hours_removed_for_duplicates,
    hours_removed_for_operating_hours: windowed.hoursRemoved,
    hours_changed_by_validation: round2(hoursChanged),
    intervals_auto_corrected: normalized.filter(n => n.validation_status === 'auto_corrected').length,
    intervals_needing_review: normalized.filter(n => n.validation_status === 'needs_review').length,
    intervals_rejected: normalized.filter(n => n.validation_status === 'rejected_or_unusable').length,
    total_normalized_timeline_hours: totalTimelineHours,
    final_approvable_hours: finalApprovable,
  };

  const report: ValidationReportRow[] = normalized.map(n => ({
    provider: n.providerName ?? input.identity.name ?? null,
    submission_id: n.submissionId ?? null,
    date: n.date ?? null,
    day_of_week: n.dayOfWeek ?? null,
    raw_time_range: `${n.raw_start_time}–${n.raw_end_time}`,
    corrected_time_range: `${n.normalized_start_time}–${n.normalized_end_time}`,
    raw_duration: n.original_duration_hours,
    corrected_duration: n.normalized_duration_hours,
    warnings: n.validation_warnings,
    correction_reason: n.correction_reason,
    used_in_forecast: n.used_in_forecast,
    needs_manual_review: n.needs_manual_review,
    validation_status: n.validation_status,
  }));

  // Detect aggregate violations and append to summary report as synthetic rows
  const dailyHours = new Map<string, number>();
  for (const s of reconciled.slots) {
    dailyHours.set(s.date, (dailyHours.get(s.date) ?? 0) + (s.endMin - s.startMin) / 60);
  }
  let daysOver = 0;
  for (const [, h] of dailyHours) if (h > config.max_daily_hours) daysOver++;
  const weeklyMax = Math.max(0, ...weeklyTotals(dailyHours));
  if (weeklyMax > config.max_weekly_hours) {
    report.push(syntheticReport(
      input.identity,
      `Weekly hours exceed threshold: max week=${weeklyMax.toFixed(1)}h > ${config.max_weekly_hours}h`,
    ));
  }
  if (daysOver > 0) {
    report.push(syntheticReport(
      input.identity,
      `${daysOver} day(s) exceed max_daily_hours=${config.max_daily_hours}h`,
    ));
  }

  return {
    identity: input.identity,
    targetMonth: input.targetMonth,
    normalized,
    timeline: reconciled.slots,
    outOfHoursTimeline: windowed.droppedSlots,
    summary,
    report,
    override_used: override,
  };
}

function weeklyTotals(dailyHours: Map<string, number>): number[] {
  const buckets = new Map<string, number>();
  for (const [date, h] of dailyHours) {
    const d = new Date(date + 'T00:00:00Z');
    if (isNaN(d.getTime())) continue;
    // ISO week start (Monday)
    const day = d.getUTCDay();
    const diff = (day + 6) % 7;
    d.setUTCDate(d.getUTCDate() - diff);
    const key = d.toISOString().slice(0, 10);
    buckets.set(key, (buckets.get(key) ?? 0) + h);
  }
  return Array.from(buckets.values());
}

function syntheticReport(identity: ProviderIdentity, message: string): ValidationReportRow {
  return {
    provider: identity.name ?? null,
    submission_id: null,
    date: null,
    day_of_week: null,
    raw_time_range: '',
    corrected_time_range: '',
    raw_duration: null,
    corrected_duration: null,
    warnings: [message],
    correction_reason: null,
    used_in_forecast: false,
    needs_manual_review: true,
    validation_status: 'needs_review',
  };
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
// === supabase/functions/_shared/submissionTimeline.ts ===
/**
 * Shared pipeline that turns a group of `schedule_submissions` rows
 * (provider + target_month) into:
 *   - the canonical normalized slot timeline (post override / AM-PM
 *     correction, dedup, unavailable subtraction)
 *   - a forecast-only sub-timeline (telehealth kinds by default)
 *   - a deterministic set of shift_recommendations rows
 *
 * Both `evaluate-schedule-submissions` and `emit-shift-recommendations`
 * MUST call this module so the two stages produce the exact same slots
 * and shift rec rows. Drift between them previously caused decisions to
 * cite hours that didn't match what was emitted to Homebase.
 *
 * IMPORTANT: This file is mirrored at
 *   supabase/functions/_shared/submissionTimeline.ts
 * for Deno edge-function consumption. Keep the two in sync.
 */

/** Shape of `schedule_submissions.parsed_shifts` produced by sync-jotform-submissions. */
export interface ParsedShiftsBlob {
  recurring_virtual?: unknown;
  one_off_virtual?: unknown;
  in_home_clinic?: unknown;
  unavailable_dates?: unknown;
  email?: string;
  [k: string]: unknown;
}

export interface SubmissionRow {
  id: string;
  submitted_at: string;
  parsed_shifts: ParsedShiftsBlob | null;
}

/**
 * Default kinds counted toward `final_approvable_hours`. In-home/clinic
 * shifts are staffed under a separate scope and capacity model, so they
 * do not consume telehealth demand-hour gaps. Override via
 * `forecastKinds` when the caller knows otherwise.
 */
export const TELEHEALTH_FORECAST_KINDS: IntervalKind[] = ['recurring', 'one_off'];

export type ShiftType = 'virtual_recurring' | 'virtual_oneoff' | 'in_home_clinic';

export interface ShiftRecommendationRow {
  submission_id: string;
  provider_id: string;
  provider_name: string;
  target_month: string;
  shift_date: string;
  start_min: number;
  end_min: number;
  hours: number;
  shift_type: ShiftType;
  assigned_state: string | null;
  recommendation: 'publish' | 'cut';
  recommendation_reason: string;
  decision_run_id: string;
  publish_status: 'pending';
}

export interface BuildTimelineOptions {
  forecastKinds?: IntervalKind[];
}

export interface BuildTimelineResult extends NormalizationResult {
  /** Subset of `timeline` filtered by forecastKinds (default = telehealth). */
  forecastTimeline: ExpandedSlot[];
  /** Subset of `outOfHoursTimeline` filtered by forecastKinds. In-home /
   *  clinic shifts are not subject to the operating-hours window so they
   *  never appear here. */
  forecastOutOfHoursTimeline: ExpandedSlot[];
}

/**
 * Run a group of submissions through the validation/normalization pipeline.
 * Both consumers must use this so the timelines match.
 */
export function buildSubmissionTimeline(
  submissions: SubmissionRow[],
  identity: ProviderIdentity,
  targetMonth: string,
  options: BuildTimelineOptions = {},
): BuildTimelineResult {
  const forecastKinds = options.forecastKinds ?? TELEHEALTH_FORECAST_KINDS;

  // Sort chronologically (later wins on overlap inside the validator).
  const ordered = [...submissions].sort((a, b) =>
    a.submitted_at.localeCompare(b.submitted_at),
  );

  const unavailableDates = collectUnavailableDates(ordered);

  const input: NormalizationInput = {
    identity,
    submissions: ordered.map(s => ({
      submissionId: s.id,
      submittedAt: s.submitted_at,
      intervals: extractRawIntervalsFromParsedShifts(s.parsed_shifts),
    })),
    targetMonth,
    unavailableDates,
    forecastKinds,
  };

  const result = normalizeProviderAvailability(input);
  const forecastSet = new Set(forecastKinds);
  const forecastTimeline = result.timeline.filter(s => forecastSet.has(s.source.kind));
  const forecastOutOfHoursTimeline = result.outOfHoursTimeline.filter(s =>
    forecastSet.has(s.source.kind),
  );
  return { ...result, forecastTimeline, forecastOutOfHoursTimeline };
}

export function extractRawIntervalsFromParsedShifts(parsed: ParsedShiftsBlob | null): RawInterval[] {
  if (!parsed) return [];
  const out: RawInterval[] = [];
  for (const e of parseWidgetArray(parsed.recurring_virtual)) {
    if (!e['Start Time (ET)'] || !e['End Time (ET)']) continue;
    out.push({
      kind: 'recurring',
      dayOfWeek: e['Day of Week'],
      rawStart: e['Start Time (ET)'],
      rawEnd: e['End Time (ET)'],
    });
  }
  for (const e of parseWidgetArray(parsed.one_off_virtual)) {
    const date = parseFormDate(e['Date']);
    if (!date || !e['Start Time (ET)'] || !e['End Time (ET)']) continue;
    out.push({
      kind: 'one_off',
      date,
      rawStart: e['Start Time (ET)'],
      rawEnd: e['End Time (ET)'],
    });
  }
  for (const e of parseWidgetArray(parsed.in_home_clinic)) {
    const date = parseFormDate(e['Date']);
    if (!date || !e['Start Time (ET)'] || !e['End Time (ET)']) continue;
    out.push({
      kind: 'in_home',
      date,
      rawStart: e['Start Time (ET)'],
      rawEnd: e['End Time (ET)'],
    });
  }
  return out;
}

export function emailFromParsedShifts(parsed: ParsedShiftsBlob | null): string | null {
  if (!parsed) return null;
  const e = parsed.email;
  return typeof e === 'string' && e.trim() ? e.trim() : null;
}

export function collectUnavailableDates(submissions: SubmissionRow[]): string[] {
  // We take the union of all listed unavailable dates across submissions in
  // the group: a provider who lists 6/15 off in their first submission and
  // forgets to re-list it in a resubmission still shouldn't be scheduled
  // there. ClinOps confirmed this is the desired behavior.
  //
  // The Jotform "When will you be unavailable to work?" widget stores rows
  // with `Start Date` / `End Date` columns and supports inclusive date
  // ranges (e.g. 06-06-2026 → 06-08-2026 means three off days). We expand
  // each range and also accept a single `Date` value as a fallback for any
  // legacy entry shape.
  const out = new Set<string>();
  for (const sub of submissions) {
    const parsed = sub.parsed_shifts;
    if (!parsed) continue;
    for (const e of parseWidgetArray(parsed.unavailable_dates)) {
      const start = parseFormDate(e['Start Date'] ?? e['Date']);
      const end = parseFormDate(e['End Date']) ?? start;
      if (!start) continue;
      for (const d of expandDateRange(start, end ?? start)) out.add(d);
    }
  }
  return Array.from(out);
}

export function parseAllocationsFromNotes(notes: string): Array<{ state: string; hours: number }> {
  const allocStr = notes.match(/alloc=([^;]+)/);
  if (!allocStr) return [];
  const out: Array<{ state: string; hours: number }> = [];
  const re = /([A-Z]{2}):([0-9.]+)h/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(allocStr[1])) !== null) {
    const hours = Number(m[2]);
    if (Number.isFinite(hours) && hours > 0) out.push({ state: m[1], hours });
  }
  return out;
}

export interface BuildShiftRecommendationsArgs {
  providerId: string;
  providerName: string;
  targetMonth: string;
  /** Full normalized timeline (all kinds). */
  timeline: ExpandedSlot[];
  /** Subset of timeline that participates in forecast cut budget. */
  forecastTimeline: ExpandedSlot[];
  /** Out-of-business-hours fragments (telehealth only). Each is emitted as
   *  its own `cut` row with reason "outside operating hours". They are
   *  not part of the forecast cut budget — they were already removed from
   *  `final_approvable_hours` upstream. */
  outOfHoursTimeline?: ExpandedSlot[];
  declinedHours: number;
  /** True if the entire forecast timeline should be cut (declined decision). */
  declineAll: boolean;
  allocations: Array<{ state: string; hours: number }>;
  decisionRunId: string;
}

const OUT_OF_HOURS_REASON =
  'Cut — outside operating hours window (9a–9p ET weekdays, 9a–12p ET weekends)';

/**
 * Cut/publish row generator shared by evaluator and emitter.
 *
 * Forecast slots (recurring_virtual / virtual_oneoff) participate in the
 * cut budget: latest-first, cut until `declinedHours` is satisfied.
 * In-home/clinic slots are not in the forecast scope, so they are always
 * `publish` and don't consume the cut budget.
 *
 * Out-of-hours fragments (passed via `outOfHoursTimeline`) are emitted as
 * their own `cut` rows so the workbench surfaces hours declined for being
 * outside business hours alongside other cuts.
 */
export function buildShiftRecommendationRows(args: BuildShiftRecommendationsArgs): ShiftRecommendationRow[] {
  const outOfHours = args.outOfHoursTimeline ?? [];
  if (args.timeline.length === 0 && outOfHours.length === 0) return [];

  const forecastSlots = new Set(args.forecastTimeline);
  const cutBudgetTotal = args.declineAll
    ? sumHours(args.forecastTimeline)
    : Math.max(0, args.declinedHours);

  // Walk forecast slots latest-first to allocate cuts.
  const sortedDesc = [...args.forecastTimeline].sort((a, b) =>
    b.date.localeCompare(a.date) || b.startMin - a.startMin,
  );
  const cutSet = new Set<ExpandedSlot>();
  let remainingCut = round2(cutBudgetTotal);
  for (const slot of sortedDesc) {
    if (remainingCut <= 0.001) break;
    cutSet.add(slot);
    remainingCut = round2(remainingCut - (slot.endMin - slot.startMin) / 60);
  }

  // Buckets for state assignment, only consumed by published forecast slots.
  const buckets = new Map<string, number>(args.allocations.map(a => [a.state, a.hours]));

  const timelineRows = args.timeline.map(slot => {
    const slotHours = round2((slot.endMin - slot.startMin) / 60);
    const isForecastSlot = forecastSlots.has(slot);
    const isCut = isForecastSlot && cutSet.has(slot);

    let assignedState: string | null = null;
    let reason: string;

    if (isCut) {
      reason = args.declineAll
        ? 'Declined — no demand-hour gap remained in any licensed state when allocator processed this provider'
        : 'Trimmed as oversupply — accepted hours capped at network demand';
    } else if (!isForecastSlot) {
      // In-home / clinic shifts: not part of the telehealth forecast.
      reason = 'Publish (in-home/clinic — not part of telehealth forecast scope)';
    } else {
      let bestState: string | null = null;
      let bestRemaining = -1;
      for (const [state, remaining] of buckets) {
        if (remaining > bestRemaining) {
          bestState = state;
          bestRemaining = remaining;
        }
      }
      assignedState = bestState;
      if (bestState) {
        buckets.set(bestState, round2((buckets.get(bestState) ?? 0) - slotHours));
      }
      reason = bestState
        ? `Publish to ${bestState} (largest remaining state gap at time of allocation)`
        : 'Publish (no state allocation; review manually)';
    }

    return {
      submission_id: slot.source.submissionId ?? '',
      provider_id: args.providerId,
      provider_name: args.providerName,
      target_month: args.targetMonth,
      shift_date: slot.date,
      start_min: slot.startMin,
      end_min: slot.endMin,
      hours: slotHours,
      shift_type: kindToShiftType(slot.source.kind),
      assigned_state: assignedState,
      recommendation: (isCut ? 'cut' : 'publish') as 'cut' | 'publish',
      recommendation_reason: reason,
      decision_run_id: args.decisionRunId,
      publish_status: 'pending' as const,
    };
  });

  const outOfHoursRows: ShiftRecommendationRow[] = outOfHours.map(slot => ({
    submission_id: slot.source.submissionId ?? '',
    provider_id: args.providerId,
    provider_name: args.providerName,
    target_month: args.targetMonth,
    shift_date: slot.date,
    start_min: slot.startMin,
    end_min: slot.endMin,
    hours: round2((slot.endMin - slot.startMin) / 60),
    shift_type: kindToShiftType(slot.source.kind),
    assigned_state: null,
    recommendation: 'cut',
    recommendation_reason: OUT_OF_HOURS_REASON,
    decision_run_id: args.decisionRunId,
    publish_status: 'pending',
  }));

  return [...timelineRows, ...outOfHoursRows].sort((a, b) =>
    a.shift_date.localeCompare(b.shift_date) || a.start_min - b.start_min,
  );
}

export function kindToShiftType(kind: IntervalKind): ShiftType {
  if (kind === 'recurring') return 'virtual_recurring';
  if (kind === 'in_home') return 'in_home_clinic';
  return 'virtual_oneoff';
}

// ─── Local widget helpers ────────────────────────────────────────────────

function parseWidgetArray(raw: unknown): Record<string, string>[] {
  if (raw == null) return [];
  let parsed: unknown = raw;
  if (typeof raw === 'string') {
    try { parsed = JSON.parse(raw); } catch { return []; }
  }
  if (!Array.isArray(parsed)) return [];
  return parsed.filter((e): e is Record<string, string> => e != null && typeof e === 'object');
}

function parseFormDate(raw: unknown): string | null {
  if (!raw) return null;
  const s = String(raw).trim();
  const mdy = s.match(/^(\d{1,2})-(\d{1,2})-(\d{4})$/);
  if (mdy) return `${mdy[3]}-${mdy[1].padStart(2, '0')}-${mdy[2].padStart(2, '0')}`;
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
  return null;
}

function expandDateRange(startISO: string, endISO: string): string[] {
  // Inclusive expansion in UTC to avoid DST drift.
  const [sy, sm, sd] = startISO.split('-').map(Number);
  const [ey, em, ed] = endISO.split('-').map(Number);
  let cur = Date.UTC(sy, sm - 1, sd);
  const last = Date.UTC(ey, em - 1, ed);
  if (!Number.isFinite(cur) || !Number.isFinite(last) || last < cur) {
    return [startISO];
  }
  const out: string[] = [];
  const DAY = 86_400_000;
  while (cur <= last) {
    const d = new Date(cur);
    out.push(
      `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`,
    );
    cur += DAY;
  }
  return out;
}

function sumHours(slots: ExpandedSlot[]): number {
  return slots.reduce((s, x) => s + (x.endMin - x.startMin) / 60, 0);
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
// === supabase/functions/evaluate-schedule-submissions/index.ts ===
/**
 * evaluate-schedule-submissions edge function
 *
 * Reads schedule_submissions and writes back a decision (accepted /
 * partial / declined) plus accepted_hours / declined_hours / decision_notes.
 *
 * Resubmission handling:
 *   When a provider submits multiple times for the same target_month, we
 *   group those submissions together and walk them chronologically. New
 *   submissions overwrite any overlapping date/time slots from earlier
 *   submissions; non-overlapping slots from earlier submissions remain.
 *   The latest submission in the group gets the decision based on the
 *   merged effective hours; earlier submissions get decision_status =
 *   'superseded' so the audit trail stays intact.
 *
 * Decision math (per group of submissions for the same provider + month):
 *   1. Run every submission's parsed_shifts through the validation /
 *      normalization pipeline (`_shared/availabilityValidation.ts`):
 *        - Apply provider-specific overrides (e.g. AM/PM corrections)
 *        - Apply default deterministic AM/PM corrections
 *        - Flag implausibly long shifts, full-day recurring availability,
 *          12 AM start/end paired with daytime end/start, etc.
 *        - Expand recurring entries to weekday occurrences in the month;
 *          one-off + in-home become single-date slots.
 *        - Reconcile across submissions: later submissions overwrite
 *          overlapping slots from earlier ones; duplicates collapse.
 *        - Subtract unavailable_dates the provider listed.
 *      The raw submission stays untouched on the row (raw_answers and the
 *      raw widget values inside parsed_shifts are preserved); only the
 *      *normalized* timeline drives the forecast decision.
 *   2. effective_hours = summary.final_approvable_hours from the pipeline
 *      (normalized + deduped + minus unavailable).
 *   3. eligible_states = provider's licensed states, filtered by the
 *      MD-only state rule: AL/IN/GA/MS/MO/SC/TN/LA can only be allocated
 *      to providers whose profession is MD or DO.
 *   4. For each eligible state, demand_hours = sum of demand_forecast
 *      values over the target month, minus committed hours from decisions
 *      made in prior runs for OTHER providers in same state+month.
 *      Note: demand_forecast.projected_visits stores hours of provider
 *      availability (not visits); column name is legacy. See
 *      compute-demand-forecast for the canonical methodology.
 *   5. total_gap = sum of demand_hours across eligible states (clipped 0).
 *   6. Decision:
 *        total_gap >= effective_hours       → accepted (all of it)
 *        0 < total_gap < effective_hours    → partial  (accept = total_gap,
 *                                                      decline = remainder)
 *        total_gap <= 0                     → declined
 *
 * Modes:
 *   POST /functions/v1/evaluate-schedule-submissions
 *     → evaluate every (provider, target_month) group with at least one
 *       pending submission
 *   POST /functions/v1/evaluate-schedule-submissions?target_month=YYYY-MM-01
 *     → evaluate every group for that month (re-runs supersedes too)
 *   POST /functions/v1/evaluate-schedule-submissions?provider_id=<uuid>
 *     → evaluate just that provider's pending groups
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
// States that can only be served by MDs/DOs per Vitable scope-of-practice rules.
// NPs licensed in these states cannot be allocated demand hours here.
const MD_ONLY_STATES = new Set(['AL', 'IN', 'GA', 'MS', 'MO', 'SC', 'TN', 'LA']);
const MD_PROFESSIONS = new Set(['MD', 'DO']);

// Mental health professions use a weekly SLA across all 50 states (no per-state
// demand allocation). They bypass the demand-gap math entirely: every parsed
// hour becomes accepted unless validation flags it. The "demand" for MH is
// staffed separately (Metabase 2973), so running them through the telehealth
// state allocator just produces false declines.
const MH_PROFESSIONS = new Set([
  'MENTAL_HEALTH_COACH',
  'MH_COACH',
  'LPC',
  'THERAPIST',
  'HEALTH_COACH',
]);
const isMentalHealthProfession = (p: string | null | undefined) => {
  if (!p) return false;
  const norm = p.toUpperCase().replace(/\s+/g, '_');
  return MH_PROFESSIONS.has(norm);
};

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

type ParsedShifts = {
  requested_states?: string[];
  recurring_virtual?: unknown;
  one_off_virtual?: unknown;
  in_home_clinic?: unknown;
  unavailable_dates?: unknown;
  email?: string;
  [k: string]: unknown;
};

type Submission = {
  id: string;
  provider_id: string | null;
  provider_name: string;
  target_month: string;
  parsed_shifts: ParsedShifts | null;
  decision_status: string;
  submitted_at: string;
};

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  const url = new URL(req.url);
  const monthFilter = url.searchParams.get('target_month');
  const providerFilter = url.searchParams.get('provider_id');

  const decisionRunId = crypto.randomUUID();
  const counters = {
    groups: 0,
    accepted: 0,
    partial: 0,
    declined: 0,
    needs_review: 0,
    superseded: 0,
    skipped_unmatched_provider: 0,
    skipped_no_hours: 0,
    skipped_no_licensed_states: 0,
    errors: 0,
  };
  const decisions: Array<Record<string, unknown>> = [];

  try {
    // ── Find groups (provider, target_month) that need work ─────────────
    let pendingQuery = supabase
      .from('schedule_submissions')
      .select('provider_id, target_month, decision_status');

    if (monthFilter) pendingQuery = pendingQuery.eq('target_month', monthFilter);
    if (providerFilter) pendingQuery = pendingQuery.eq('provider_id', providerFilter);
    if (!monthFilter && !providerFilter) {
      // Pick up new pending rows AND previously-flagged needs_review rows so
      // a re-run after fixing the override config or raw entry decides them.
      pendingQuery = pendingQuery.in('decision_status', ['pending', 'needs_review']);
    }
    pendingQuery = pendingQuery.range(0, 49999);

    const { data: pendingRows, error: pErr } = await pendingQuery;
    if (pErr) throw new Error(`Pending lookup failed: ${pErr.message}`);

    // Skip historical submissions in the default eval — past months can't be
    // re-decided operationally, and demand_forecast doesn't have rows for
    // them. An explicit ?target_month= bypass remains for backfill.
    const currentMonth = (() => {
      const d = new Date();
      return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-01`;
    })();

    const groupKeys = new Set<string>();
    for (const r of pendingRows ?? []) {
      if (!r.provider_id || !r.target_month) continue;
      if (!monthFilter && !providerFilter && r.target_month < currentMonth) continue;
      groupKeys.add(`${r.provider_id}|${r.target_month}`);
    }

    if (groupKeys.size === 0) {
      return json({
        ok: true, decision_run_id: decisionRunId, ...counters,
        message: 'No groups with pending submissions',
      });
    }

    // ── Load every submission in those groups ──────────────────────────
    const providerIds = Array.from(new Set(
      Array.from(groupKeys).map(k => k.split('|')[0])
    ));
    const months = Array.from(new Set(
      Array.from(groupKeys).map(k => k.split('|')[1])
    ));

    const { data: subsRaw, error: sErr } = await supabase
      .from('schedule_submissions')
      .select('id, provider_id, provider_name, target_month, parsed_shifts, decision_status, submitted_at')
      .in('provider_id', providerIds)
      .in('target_month', months);
    if (sErr) throw new Error(`Submissions load failed: ${sErr.message}`);

    const submissions = (subsRaw ?? []) as Submission[];
    const submissionsByGroup = new Map<string, Submission[]>();
    for (const s of submissions) {
      if (!s.provider_id) continue;
      const k = `${s.provider_id}|${s.target_month}`;
      if (!groupKeys.has(k)) continue;
      if (!submissionsByGroup.has(k)) submissionsByGroup.set(k, []);
      submissionsByGroup.get(k)!.push(s);
    }

    // ── Preload provider profession (for MD-only state enforcement) ────
    const professionByProvider = new Map<string, string | null>();
    if (providerIds.length > 0) {
      const { data: provs } = await supabase
        .from('providers')
        .select('id, profession')
        .in('id', providerIds);
      for (const p of provs ?? []) {
        professionByProvider.set(p.id, p.profession ?? null);
      }
    }

    // ── Preload provider licenses (filtered by MD-only constraint) ─────
    // For the eight MD-only states, only providers whose profession is MD/DO
    // are eligible — even if an NP holds a valid license. Drop non-eligible
    // (provider, state) pairs at preload time so the allocator never sees them.
    const licensedStatesByProvider = new Map<string, Set<string>>();
    if (providerIds.length > 0) {
      const { data: licenses } = await supabase
        .from('provider_licenses')
        .select('provider_id, state, status')
        .in('provider_id', providerIds);
      for (const l of licenses ?? []) {
        if (!l.provider_id || !l.state) continue;
        if (l.status && !['active', 'verified', 'pending_renewal'].includes(l.status)) continue;
        const st = String(l.state).trim().toUpperCase();
        const profession = (professionByProvider.get(l.provider_id) ?? '').toUpperCase();
        if (MD_ONLY_STATES.has(st) && !MD_PROFESSIONS.has(profession)) continue;
        if (!licensedStatesByProvider.has(l.provider_id)) {
          licensedStatesByProvider.set(l.provider_id, new Set());
        }
        licensedStatesByProvider.get(l.provider_id)!.add(st);
      }
    }

    // ── Preload baseline demand per (state, month) ──────────────────────
    // Reads from v_monthly_demand which pre-aggregates demand_forecast to one
    // row per (state, month). Querying the raw demand_forecast directly hits
    // PostgREST's silent row truncation at ~1,000 rows (a full month is 1,410
    // rows), which previously dropped PA from the result set entirely.
    const demandByKey = new Map<string, number>(); // `${state}_${month}` → total visits
    if (months.length > 0) {
      const { data: rows, error: dErr } = await supabase
        .from('v_monthly_demand')
        .select('state, month, total_visits')
        .in('month', months);
      if (dErr) throw new Error(`Demand load failed: ${dErr.message}`);
      for (const r of rows ?? []) {
        const st = String(r.state).trim().toUpperCase();
        const month = String(r.month);
        const k = `${st}_${month}`;
        demandByKey.set(k, Number(r.total_visits ?? 0));
      }
    }

    // ── Preload committed hours from OTHER groups (not in scope) ────────
    const groupKeysInScope = groupKeys;
    const committedByKey = new Map<string, number>(); // `${state}_${month}` → committed hours
    if (months.length > 0) {
      const { data: committed } = await supabase
        .from('schedule_submissions')
        .select('id, provider_id, target_month, parsed_shifts, accepted_hours, decision_status')
        .in('target_month', months)
        .in('decision_status', ['accepted', 'partial'])
        .range(0, 49999);

      // Sum accepted_hours per (state, month) for groups NOT being re-evaluated.
      // Best-effort even-split across the provider's licensed states for that month.
      for (const c of committed ?? []) {
        if (!c.provider_id || !c.target_month) continue;
        const k = `${c.provider_id}|${c.target_month}`;
        if (groupKeysInScope.has(k)) continue;
        const hours = typeof c.accepted_hours === 'number' ? c.accepted_hours : 0;
        if (hours <= 0) continue;
        const states = licensedStatesByProvider.get(c.provider_id);
        if (!states || states.size === 0) continue;
        const perState = hours / states.size;
        for (const st of states) {
          const key = `${st}_${c.target_month}`;
          committedByKey.set(key, (committedByKey.get(key) ?? 0) + perState);
        }
      }
    }

    // ── Sort groups: most-constrained providers first ──────────────────
    // Process providers with the fewest licensed-states-with-demand first so
    // they don't get bumped by multi-state providers who have alternatives.
    // This is the practical heuristic for "maximize utilization across
    // providers" — single-state providers grab their state's gap before
    // flexible providers consume it.
    const groupKeysSorted = Array.from(submissionsByGroup.keys()).sort((a, b) => {
      const [provA, monthA] = a.split('|');
      const [provB, monthB] = b.split('|');
      const licA = licensedStatesByProvider.get(provA) ?? new Set();
      const licB = licensedStatesByProvider.get(provB) ?? new Set();
      const countWithDemand = (states: Set<string>, month: string) =>
        Array.from(states).filter(s => (demandByKey.get(`${s}_${month}`) ?? 0) > 0).length;
      const cA = countWithDemand(licA, monthA);
      const cB = countWithDemand(licB, monthB);
      if (cA !== cB) return cA - cB;        // fewer licensed-with-demand first
      return monthA.localeCompare(monthB);  // stable tiebreaker
    });

    // ── Evaluate each group ─────────────────────────────────────────────
    for (const key of groupKeysSorted) {
      const groupSubs = submissionsByGroup.get(key)!;
      try {
        counters.groups++;
        const [providerId, targetMonth] = key.split('|');

        // Sort chronologically; latest is the one that carries the decision
        groupSubs.sort((a, b) => a.submitted_at.localeCompare(b.submitted_at));
        const latest = groupSubs[groupSubs.length - 1];
        const olderIds = groupSubs.slice(0, -1).map(s => s.id);

        if (!providerId) {
          counters.skipped_unmatched_provider++;
          decisions.push({ group: key, status: 'skipped', reason: 'unmatched_provider' });
          continue;
        }

        // Build merged slot timeline via the shared validation/normalization
        // pipeline. emit-shift-recommendations runs the SAME function with
        // the SAME inputs, so timelines match.
        // Raw submission data on the row is preserved verbatim — we only
        // read it here.
        const validation: BuildTimelineResult = buildSubmissionTimeline(
          groupSubs.map(s => ({
            id: s.id,
            submitted_at: s.submitted_at,
            parsed_shifts: s.parsed_shifts ?? null,
          })),
          {
            providerId,
            email: emailFromParsedShifts(latest.parsed_shifts),
            name: latest.provider_name,
          },
          targetMonth,
        );
        const fullTimeline = validation.timeline;
        const forecastTimeline = validation.forecastTimeline;
        const forecastOutOfHoursTimeline = validation.forecastOutOfHoursTimeline;
        const effectiveHours = validation.summary.final_approvable_hours;
        // Hours dropped because the slot fell outside the operating-hours
        // window (9a-9p ET weekdays, 9a-12p ET weekends). They count toward
        // declined_hours so the provider sees the full reason their submitted
        // time was not approved.
        const oohDeclined = round2(validation.summary.hours_removed_for_operating_hours ?? 0);

        if (validation.report.length > 0) {
          console.log(`[validation] ${latest.provider_name} ${targetMonth}`,
            JSON.stringify({
              summary: validation.summary,
              report: validation.report,
            }));
        }

        // ── needs_review short-circuit ────────────────────────────────────
        // If validation surfaced intervals that need a human eyeball, do NOT
        // auto-decide the group. The latest submission gets decision_status
        // 'needs_review' with accepted=0 and declined=0; older submissions
        // are still superseded so the audit trail is intact. ClinOps can
        // re-run after the override config or raw entry is fixed.
        const needsReview = validation.summary.intervals_needing_review > 0
          || validation.summary.intervals_rejected > 0;
        if (needsReview) {
          if (olderIds.length) {
            await markSuperseded(supabase, olderIds, decisionRunId, `Superseded by latest submission ${latest.id}`);
            counters.superseded += olderIds.length;
          }
          const reviewReasons = validation.report
            .filter(r => r.needs_manual_review)
            .map(r => `${r.day_of_week ?? r.date ?? ''} ${r.raw_time_range}: ${r.warnings.join('; ')}`)
            .slice(0, 8);
          const notes = [
            `decision=needs_review`,
            `intervals_needing_review=${validation.summary.intervals_needing_review}`,
            `intervals_rejected=${validation.summary.intervals_rejected}`,
            `raw_hours=${validation.summary.raw_total_hours}h`,
            `forecastable_hours=${effectiveHours}h`,
            `reasons=${reviewReasons.join(' | ') || '(see validation_report)'}`,
          ].join('; ');
          await writeDecision(supabase, latest.id, {
            status: 'needs_review',
            accepted_hours: 0,
            declined_hours: 0,
            notes,
            decision_run_id: decisionRunId,
            validation,
          });
          counters.needs_review++;
          decisions.push({
            group: key,
            provider: latest.provider_name,
            target_month: targetMonth,
            status: 'needs_review',
            superseded: olderIds.length,
            validation_summary: validation.summary,
            validation_report: validation.report,
          });
          continue;
        }

        if (effectiveHours <= 0) {
          counters.skipped_no_hours++;
          // Mark older as superseded; latest becomes 'declined' with note
          await markSuperseded(supabase, olderIds, decisionRunId, `Superseded by ${latest.id}; group has 0 effective hours`);
          const noHoursNotes = oohDeclined > 0
            ? `No effective hours in any submission for this provider+month; hours_removed_outside_business_hours=${oohDeclined}h`
            : 'No effective hours in any submission for this provider+month';
          await writeDecision(supabase, latest.id, {
            status: 'declined',
            accepted_hours: 0,
            declined_hours: oohDeclined,
            notes: noHoursNotes,
            decision_run_id: decisionRunId,
            validation,
          });
          if (oohDeclined > 0 || forecastOutOfHoursTimeline.length > 0) {
            const oohRecRows = buildShiftRecommendationRows({
              providerId,
              providerName: latest.provider_name,
              targetMonth,
              timeline: [],
              forecastTimeline: [],
              outOfHoursTimeline: forecastOutOfHoursTimeline,
              declinedHours: 0,
              declineAll: false,
              allocations: [],
              decisionRunId,
            });
            await writeShiftRecommendations(supabase, groupSubs.map(s => s.id), oohRecRows);
          }
          counters.declined++;
          counters.superseded += olderIds.length;
          decisions.push({ group: key, provider: latest.provider_name, target_month: targetMonth, status: 'declined', reason: 'no_hours', superseded: olderIds.length });
          continue;
        }

        // ── Mental health bypass ────────────────────────────────────────────
        // MH coaches/LPCs serve all 50 states with a weekly SLA, separate from
        // the telehealth state-demand pipeline. Accept every validated hour
        // and skip the licensed-states + state-gap math.
        const profession = professionByProvider.get(providerId);
        if (isMentalHealthProfession(profession)) {
          if (olderIds.length) {
            await markSuperseded(supabase, olderIds, decisionRunId, `Superseded by latest submission ${latest.id}`);
            counters.superseded += olderIds.length;
          }
          const mhNoteParts = [
            `decision=accepted (mental_health_bypass)`,
            `profession=${profession}`,
            `effective_hours=${effectiveHours}h`,
            `raw_hours=${validation.summary.raw_total_hours}h`,
            'note=MH uses weekly SLA across 50 states; bypasses state demand allocator',
          ];
          if (oohDeclined > 0) {
            mhNoteParts.push(`hours_removed_outside_business_hours=${oohDeclined}h`);
          }
          await writeDecision(supabase, latest.id, {
            status: 'accepted',
            accepted_hours: effectiveHours,
            declined_hours: oohDeclined,
            notes: mhNoteParts.join('; '),
            decision_run_id: decisionRunId,
            validation,
          });
          counters.accepted++;
          decisions.push({
            group: key,
            provider: latest.provider_name,
            target_month: targetMonth,
            status: 'accepted',
            accepted_hours: effectiveHours,
            declined_hours: oohDeclined,
            mh_bypass: true,
            superseded: olderIds.length,
          });
          continue;
        }

        // Eligible states = provider's licensed states (form has no state field)
        const licensed = licensedStatesByProvider.get(providerId) ?? new Set<string>();
        if (licensed.size === 0) {
          counters.skipped_no_licensed_states++;
          await markSuperseded(supabase, olderIds, decisionRunId, `Superseded by ${latest.id}; provider has no active licenses`);
          const noLicNoteParts = ['Provider has no active licenses on file'];
          if (oohDeclined > 0) {
            noLicNoteParts.push(`hours_removed_outside_business_hours=${oohDeclined}h`);
          }
          await writeDecision(supabase, latest.id, {
            status: 'declined',
            accepted_hours: 0,
            declined_hours: round2(effectiveHours + oohDeclined),
            notes: noLicNoteParts.join('; '),
            decision_run_id: decisionRunId,
            validation,
          });
          counters.declined++;
          counters.superseded += olderIds.length;
          decisions.push({ group: key, provider: latest.provider_name, target_month: targetMonth, status: 'declined', reason: 'no_licenses', superseded: olderIds.length });
          continue;
        }

        // Compute remaining demand-hour gap per state
        const gapByState: Array<{ state: string; gapHours: number; missingDemand: boolean }> = [];
        for (const st of licensed) {
          const dKey = `${st}_${targetMonth}`;
          const visits = demandByKey.get(dKey);
          if (visits === undefined) {
            gapByState.push({ state: st, gapHours: 0, missingDemand: true });
            continue;
          }
          // demand_forecast.projected_visits stores hours of provider
          // availability (column name is legacy/misleading), so the value
          // already IS the demand hour figure — no conversion.
          const demandHours = visits;
          const committed = committedByKey.get(dKey) ?? 0;
          gapByState.push({
            state: st,
            gapHours: Math.max(0, demandHours - committed),
            missingDemand: false,
          });
        }
        gapByState.sort((a, b) => b.gapHours - a.gapHours);
        const totalGap = round2(gapByState.reduce((s, g) => s + g.gapHours, 0));
        const missingDemandStates = gapByState.filter(g => g.missingDemand).map(g => g.state);

        // Decide. `declined` rolls up forecast cuts AND hours dropped for
        // being outside the operating-hours window so the provider sees
        // every hour we couldn't approve, not just the demand-driven cuts.
        let status: 'accepted' | 'partial' | 'declined';
        let accepted: number;
        let forecastDeclined: number;
        if (totalGap <= 0) {
          status = 'declined';
          accepted = 0;
          forecastDeclined = effectiveHours;
        } else if (totalGap >= effectiveHours) {
          status = 'accepted';
          accepted = effectiveHours;
          forecastDeclined = 0;
        } else {
          status = 'partial';
          accepted = totalGap;
          forecastDeclined = round2(effectiveHours - accepted);
        }
        const declined = round2(forecastDeclined + oohDeclined);

        // Allocate accepted hours greedily across states
        const allocations: Array<{ state: string; hours: number }> = [];
        let remaining = accepted;
        for (const g of gapByState) {
          if (remaining <= 0 || g.gapHours <= 0) break;
          const take = Math.min(g.gapHours, remaining);
          if (take > 0) {
            allocations.push({ state: g.state, hours: round2(take) });
            remaining -= take;
          }
        }

        const noteParts: string[] = [];
        noteParts.push(`group_size=${groupSubs.length}`);
        noteParts.push(`effective_hours=${effectiveHours}h`);
        noteParts.push(`raw_hours=${validation.summary.raw_total_hours}h`);
        if (validation.summary.intervals_auto_corrected > 0) {
          noteParts.push(`auto_corrected=${validation.summary.intervals_auto_corrected}`);
        }
        if (validation.summary.intervals_needing_review > 0) {
          noteParts.push(`needs_review=${validation.summary.intervals_needing_review}`);
        }
        if (validation.summary.intervals_rejected > 0) {
          noteParts.push(`rejected=${validation.summary.intervals_rejected}`);
        }
        if (validation.summary.hours_removed_for_unavailability > 0) {
          noteParts.push(`hours_removed_unavailable=${validation.summary.hours_removed_for_unavailability}h`);
        }
        if (validation.summary.hours_removed_for_duplicates > 0) {
          noteParts.push(`hours_removed_dup=${validation.summary.hours_removed_for_duplicates}h`);
        }
        if (oohDeclined > 0) {
          noteParts.push(`hours_removed_outside_business_hours=${oohDeclined}h`);
        }
        noteParts.push(`total_gap=${totalGap}h`);
        noteParts.push(
          'state_gaps=' + gapByState.map(g => `${g.state}:${g.missingDemand ? 'no_data' : round2(g.gapHours) + 'h'}`).join(','),
        );
        if (allocations.length) {
          noteParts.push('alloc=' + allocations.map(a => `${a.state}:${a.hours}h`).join(','));
        }
        if (missingDemandStates.length) {
          noteParts.push(`missing_demand=${missingDemandStates.join(',')}`);
        }
        if (olderIds.length) noteParts.push(`supersedes=${olderIds.length}`);

        // Mark older as superseded
        if (olderIds.length) {
          await markSuperseded(supabase, olderIds, decisionRunId, `Superseded by latest submission ${latest.id}`);
          counters.superseded += olderIds.length;
        }

        await writeDecision(supabase, latest.id, {
          status,
          accepted_hours: accepted,
          declined_hours: declined,
          notes: noteParts.join('; '),
          decision_run_id: decisionRunId,
          validation,
        });

        // Emit per-shift recommendations using the SAME shared row builder
        // that emit-shift-recommendations uses. This guarantees the rows
        // produced here match what a subsequent emit run would produce for
        // the same (provider, target_month).
        const recRows = buildShiftRecommendationRows({
          providerId,
          providerName: latest.provider_name,
          targetMonth,
          timeline: fullTimeline,
          forecastTimeline,
          outOfHoursTimeline: forecastOutOfHoursTimeline,
          // Forecast cut budget is the demand-driven decline only — out-of-
          // hours fragments are handled separately inside the row builder.
          declinedHours: forecastDeclined,
          declineAll: status === 'declined',
          allocations,
          decisionRunId,
        });
        await writeShiftRecommendations(supabase, groupSubs.map(s => s.id), recRows);

        if (status === 'accepted') counters.accepted++;
        else if (status === 'partial') counters.partial++;
        else counters.declined++;

        decisions.push({
          group: key,
          provider: latest.provider_name,
          target_month: targetMonth,
          group_size: groupSubs.length,
          superseded: olderIds.length,
          effective_hours: effectiveHours,
          total_gap_hours: totalGap,
          status,
          accepted_hours: accepted,
          declined_hours: declined,
          allocations,
          validation_summary: validation.summary,
          validation_report: validation.report,
        });

        // Update committed map so subsequent groups in this run see this allocation
        if (accepted > 0 && allocations.length) {
          for (const a of allocations) {
            const dKey = `${a.state}_${targetMonth}`;
            committedByKey.set(dKey, (committedByKey.get(dKey) ?? 0) + a.hours);
          }
        }
      } catch (e) {
        counters.errors++;
        const message = e instanceof Error ? e.message : String(e);
        decisions.push({ group: key, status: 'error', error: message });
        console.error('Evaluate error', key, message);
      }
    }

    return json({ ok: true, decision_run_id: decisionRunId, ...counters, decisions });
  } catch (err) {
    return json({ error: err instanceof Error ? err.message : String(err), decision_run_id: decisionRunId, ...counters }, 500);
  }
});

// ── DB writes ─────────────────────────────────────────────────────────────
async function writeDecision(
  supabase: ReturnType<typeof createClient>,
  submissionId: string,
  decision: {
    status: 'accepted' | 'partial' | 'declined' | 'needs_review';
    accepted_hours: number;
    declined_hours: number;
    notes: string;
    decision_run_id: string;
    validation: BuildTimelineResult;
  },
) {
  const { summary } = decision.validation;
  const normalizedSlots = decision.validation.timeline.map(s => ({
    date: s.date,
    start_min: s.startMin,
    end_min: s.endMin,
    hours: round2((s.endMin - s.startMin) / 60),
    kind: s.source.kind,
    source_submission_id: s.source.submissionId ?? null,
    correction_reason: s.source.correction_reason,
    validation_status: s.source.validation_status,
  }));
  const validationWarnings = Array.from(new Set(
    decision.validation.report.flatMap(r => r.warnings),
  ));

  const { error } = await supabase
    .from('schedule_submissions')
    .update({
      decision_status: decision.status,
      accepted_hours: decision.accepted_hours,
      declined_hours: decision.declined_hours,
      decision_notes: decision.notes,
      decided_at: new Date().toISOString(),
      decision_run_id: decision.decision_run_id,
      validation_status: validationStatusForGroup(decision.status, summary),
      raw_requested_hours: summary.raw_total_hours,
      normalized_requested_hours: summary.normalized_total_hours,
      effective_hours_used_for_forecast: summary.final_approvable_hours,
      validation_warnings: validationWarnings,
      normalized_slots: normalizedSlots,
      intervals_auto_corrected: summary.intervals_auto_corrected,
      intervals_needing_review: summary.intervals_needing_review,
      hours_removed_for_unavailability: summary.hours_removed_for_unavailability,
      hours_removed_for_duplicates: summary.hours_removed_for_duplicates,
      hours_changed_by_validation: summary.hours_changed_by_validation,
      validation_summary: summary,
    })
    .eq('id', submissionId);
  if (error) throw new Error(error.message);
}

function validationStatusForGroup(
  decisionStatus: 'accepted' | 'partial' | 'declined' | 'needs_review',
  summary: BuildTimelineResult['summary'],
): string {
  if (decisionStatus === 'needs_review') return 'needs_review';
  if (summary.intervals_rejected > 0) return 'partially_rejected';
  if (summary.intervals_auto_corrected > 0) return 'auto_corrected';
  return 'valid';
}

type PreservedPublishState = {
  publish_status: string;
  published_at: string | null;
  published_by: string | null;
  ehr_posted_at: string | null;
  ehr_posted_by: string | null;
  homebase_shift_id: string | null;
};

const shiftKey = (r: {
  submission_id: string;
  shift_date: string;
  start_min: number;
  end_min: number;
  shift_type: string;
}) =>
  `${r.submission_id}|${r.shift_date}|${r.start_min}|${r.end_min}|${r.shift_type}`;

async function writeShiftRecommendations(
  supabase: ReturnType<typeof createClient>,
  submissionIds: string[],
  rows: ShiftRecommendationRow[],
) {
  // Snapshot the existing publish state for this group BEFORE we wipe, so a
  // re-run of the evaluator doesn't reset Sarabjeet's "Posted to Homebase /
  // EHR" progress. We carry the state forward onto any freshly emitted shift
  // whose natural identity (submission + date + start/end + type) matches.
  // Shifts that no longer exist in the new emission lose their state — that's
  // intentional: the schedule changed, and Sarabjeet would need to re-publish.
  const { data: priorRows, error: priorErr } = await supabase
    .from('shift_recommendations')
    .select(
      'id, submission_id, provider_id, provider_name, target_month, shift_date, start_min, end_min, shift_type, publish_status, published_at, published_by, ehr_posted_at, ehr_posted_by, homebase_shift_id',
    )
    .in('submission_id', submissionIds);
  if (priorErr) {
    throw new Error(`failed to read prior shift_recommendations: ${priorErr.message}`);
  }

  const priorByKey = new Map<string, typeof priorRows[number]>();
  for (const r of priorRows ?? []) priorByKey.set(shiftKey(r), r);

  await supabase
    .from('shift_recommendations')
    .delete()
    .in('submission_id', submissionIds);

  if (rows.length === 0) return;

  // Preserve onto matching new rows.
  const preservedAuditEntries: Record<string, unknown>[] = [];
  const merged = rows.map(row => {
    const prior = priorByKey.get(shiftKey(row));
    if (!prior) return row;
    const carry: PreservedPublishState = {
      publish_status: prior.publish_status,
      published_at: prior.published_at,
      published_by: prior.published_by,
      ehr_posted_at: prior.ehr_posted_at,
      ehr_posted_by: prior.ehr_posted_by,
      homebase_shift_id: prior.homebase_shift_id,
    };
    if (carry.publish_status === 'published_to_homebase' || carry.publish_status === 'confirmed') {
      preservedAuditEntries.push({
        submission_id: row.submission_id,
        provider_id: row.provider_id,
        provider_name: row.provider_name,
        target_month: row.target_month,
        shift_date: row.shift_date,
        start_min: row.start_min,
        end_min: row.end_min,
        shift_type: row.shift_type,
        step: 'homebase',
        action: 'preserved',
        actor_label: 'evaluator re-run',
        notes: `Carried forward from prior shift ${prior.id}`,
      });
    }
    if (carry.publish_status === 'confirmed' || carry.ehr_posted_at) {
      preservedAuditEntries.push({
        submission_id: row.submission_id,
        provider_id: row.provider_id,
        provider_name: row.provider_name,
        target_month: row.target_month,
        shift_date: row.shift_date,
        start_min: row.start_min,
        end_min: row.end_min,
        shift_type: row.shift_type,
        step: 'ehr',
        action: 'preserved',
        actor_label: 'evaluator re-run',
        notes: `Carried forward from prior shift ${prior.id}`,
      });
    }
    return { ...row, ...carry };
  });

  const CHUNK = 500;
  for (let i = 0; i < merged.length; i += CHUNK) {
    const chunk = merged.slice(i, i + CHUNK);
    const { error } = await supabase.from('shift_recommendations').insert(chunk);
    if (error) throw new Error(`shift_recommendations insert failed: ${error.message}`);
  }

  // Best-effort audit. We log preservation events so it's traceable when
  // someone wonders why a published-to-Homebase shift is still checked after
  // a re-evaluation (or, if it isn't, why not).
  if (preservedAuditEntries.length > 0) {
    for (let i = 0; i < preservedAuditEntries.length; i += CHUNK) {
      const chunk = preservedAuditEntries.slice(i, i + CHUNK);
      const { error: auditErr } = await supabase.from('publish_audit_log').insert(chunk);
      if (auditErr) {
        // Don't fail the whole evaluator on a logging failure.
        console.warn('publish_audit_log preservation insert failed:', auditErr.message);
      }
    }
  }
}

async function markSuperseded(
  supabase: ReturnType<typeof createClient>,
  ids: string[],
  decisionRunId: string,
  note: string,
) {
  if (ids.length === 0) return;
  const { error } = await supabase
    .from('schedule_submissions')
    .update({
      decision_status: 'superseded',
      accepted_hours: 0,
      declined_hours: 0,
      decision_notes: note,
      decided_at: new Date().toISOString(),
      decision_run_id: decisionRunId,
    })
    .in('id', ids);
  if (error) throw new Error(error.message);
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}
