#!/usr/bin/env bash
# bundle-edge-function.sh
#
# Inlines a Deno edge function with its `_shared` dependencies into a single
# self-contained TS file. Used by deploy paths that can't ship multiple files
# with relative imports (e.g. emergency deploys via the Supabase MCP server,
# which expects content embedded in a single tool call).
#
# Inputs : path to entrypoint, e.g. supabase/functions/foo/index.ts
# Output : single-file bundle written to supabase/functions/_bundles/foo.bundle.ts
#
# Behaviour:
#   - Inlines _shared/*.ts files in dependency order before the entrypoint.
#   - Strips relative imports (./ and ../) so all symbols live at module scope.
#   - Preserves every behavioural code path (no comment/JSDoc removal beyond
#     standard whitespace normalization, no synthetic-row pruning).
#   - Keeps external https:// imports intact.
#
# Usage:
#   ./scripts/bundle-edge-function.sh supabase/functions/evaluate-schedule-submissions/index.ts
#
# This script is intentionally simple. Prefer the Supabase CLI
# (`supabase functions deploy`) when possible; bundling is only needed for
# the MCP deploy path where multi-file payloads can exceed tool size limits.

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <path/to/edge/function/index.ts>" >&2
  exit 1
fi

ENTRY="$1"
if [[ ! -f "$ENTRY" ]]; then
  echo "Entrypoint not found: $ENTRY" >&2
  exit 1
fi

FUNC_DIR="$(dirname "$ENTRY")"
FUNC_NAME="$(basename "$FUNC_DIR")"
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SHARED_DIR="$ROOT_DIR/supabase/functions/_shared"
OUT_DIR="$ROOT_DIR/supabase/functions/_bundles"
OUT_FILE="$OUT_DIR/${FUNC_NAME}.bundle.ts"

mkdir -p "$OUT_DIR"

# Order matters: leaves of the import graph first.
#   nameNormalization     (no deps)
#   availabilityOverrides (no deps; types + AVAILABILITY_OVERRIDES)
#   availabilityValidation (depends on the two above)
#   submissionTimeline    (depends on availabilityValidation)
#   <entrypoint>
SHARED_FILES=(
  "$SHARED_DIR/nameNormalization.ts"
  "$SHARED_DIR/availabilityOverrides.ts"
  "$SHARED_DIR/availabilityValidation.ts"
  "$SHARED_DIR/submissionTimeline.ts"
)

strip_local_imports() {
  perl -0777 -pe '
    # Multi-line: import { ... } from "./..."  or  "../..."
    s/import\s*\{[^}]*\}\s*from\s*[\x27"]\.\.?[^\x27"]*[\x27"];?\s*\n?//g;
    # Single-name imports
    s/import\s+\w[\w\d_]*\s+from\s*[\x27"]\.\.?[^\x27"]*[\x27"];?\s*\n?//g;
    # export { ... } from "./..."  re-exports
    s/export\s+(?:type\s+)?\{[^}]*\}\s*from\s*[\x27"]\.\.?[^\x27"]*[\x27"];?\s*\n?//g;
  '
}

relpath_from_root() {
  local path="$1"
  if [[ "$path" != /* ]]; then
    path="$ROOT_DIR/${path#./}"
  fi
  case "$path" in
    "$ROOT_DIR"/*) printf '%s\n' "${path#$ROOT_DIR/}" ;;
    *) printf '%s\n' "$path" ;;
  esac
}

{
  cat <<'BANNER'
// AUTOGENERATED — do not edit by hand.
// Source: see supabase/functions/<name>/index.ts and supabase/functions/_shared/*.ts
// Regenerate with: ./scripts/bundle-edge-function.sh <entrypoint>
// This file is committed so the deployed edge function code is byte-reproducible
// from the repo even when shipping via the Supabase MCP single-file path.

BANNER
  for f in "${SHARED_FILES[@]}"; do
    echo "// === $(relpath_from_root "$f") ==="
    strip_local_imports < "$f"
  done
  echo "// === $(relpath_from_root "$ENTRY") ==="
  strip_local_imports < "$ENTRY"
} > "$OUT_FILE"

# Sanity: zero remaining relative imports
if grep -nE "from\s+['\"]\.\.?/" "$OUT_FILE"; then
  echo "ERROR: $OUT_FILE still contains relative imports. Bundling logic needs an update." >&2
  exit 1
fi

echo "Wrote $(wc -l < "$OUT_FILE") lines, $(wc -c < "$OUT_FILE") bytes to $OUT_FILE"
