// This file is automatically generated. Do not edit it directly.
// Source: bbquooftytwprllipcsb (ClinOps scheduling project)
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type ClinOpsDatabase = {
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      coverage_gaps_daily: {
        Row: {
          computed_at: string
          date: string
          gap: number
          projected_demand: number
          scheduled_capacity: number
          state: string
          status: string
        }
        Insert: {
          computed_at?: string
          date: string
          gap: number
          projected_demand: number
          scheduled_capacity: number
          state: string
          status: string
        }
        Update: {
          computed_at?: string
          date?: string
          gap?: number
          projected_demand?: number
          scheduled_capacity?: number
          state?: string
          status?: string
        }
        Relationships: []
      }
      demand_forecast: {
        Row: {
          computed_at: string
          date: string
          forecast_run_id: string
          is_baseline: boolean
          projected_visits: number
          state: string
        }
        Insert: {
          computed_at?: string
          date: string
          forecast_run_id: string
          is_baseline?: boolean
          projected_visits: number
          state: string
        }
        Update: {
          computed_at?: string
          date?: string
          forecast_run_id?: string
          is_baseline?: boolean
          projected_visits?: number
          state?: string
        }
        Relationships: []
      }
      monthly_appointment_totals: {
        Row: {
          completed_appointments: number | null
          data_source: string | null
          id: string
          imported_at: string
          month_start: string
          notes: string | null
          total_appointments: number | null
          total_wages_paid: number | null
        }
        Insert: {
          completed_appointments?: number | null
          data_source?: string | null
          id?: string
          imported_at?: string
          month_start: string
          notes?: string | null
          total_appointments?: number | null
          total_wages_paid?: number | null
        }
        Update: {
          completed_appointments?: number | null
          data_source?: string | null
          id?: string
          imported_at?: string
          month_start?: string
          notes?: string | null
          total_appointments?: number | null
          total_wages_paid?: number | null
        }
        Relationships: []
      }
      provider_licenses: {
        Row: {
          created_at: string
          expiration_date: string | null
          id: string
          license_number: string | null
          provider_id: string
          state: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          expiration_date?: string | null
          id?: string
          license_number?: string | null
          provider_id: string
          state: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          expiration_date?: string | null
          id?: string
          license_number?: string | null
          provider_id?: string
          state?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      provider_pay_rates: {
        Row: {
          created_at: string
          effective_from: string
          effective_to: string | null
          hourly_rate: number
          id: string
          provider_id: string
          role: string | null
          source: string
        }
        Insert: {
          created_at?: string
          effective_from: string
          effective_to?: string | null
          hourly_rate: number
          id?: string
          provider_id: string
          role?: string | null
          source?: string
        }
        Update: {
          created_at?: string
          effective_from?: string
          effective_to?: string | null
          hourly_rate?: number
          id?: string
          provider_id?: string
          role?: string | null
          source?: string
        }
        Relationships: []
      }
      provider_state_active: {
        Row: {
          is_active: boolean
          provider_id: string
          state: string
          synced_at: string
        }
        Insert: {
          is_active?: boolean
          provider_id: string
          state: string
          synced_at?: string
        }
        Update: {
          is_active?: boolean
          provider_id?: string
          state?: string
          synced_at?: string
        }
        Relationships: []
      }
      provider_utilization_daily: {
        Row: {
          created_at: string
          data_source: string
          date: string
          id: string
          provider_id: string
          utilization_pct: number
        }
        Insert: {
          created_at?: string
          data_source: string
          date: string
          id?: string
          provider_id: string
          utilization_pct: number
        }
        Update: {
          created_at?: string
          data_source?: string
          date?: string
          id?: string
          provider_id?: string
          utilization_pct?: number
        }
        Relationships: []
      }
      providers: {
        Row: {
          active: boolean
          athena_provider_id: string | null
          created_at: string
          ehr_activation_status: string
          email: string | null
          employment_status: string | null
          employment_type: string | null
          homebase_employee_id: string | null
          id: string
          is_in_home: boolean
          is_telemedicine: boolean
          medallion_provider_id: string | null
          name: string
          npi: string | null
          profession: string | null
          readiness_status: string
          shift_types: string[]
          source: string | null
          updated_at: string
        }
        Insert: {
          active?: boolean
          athena_provider_id?: string | null
          created_at?: string
          ehr_activation_status?: string
          email?: string | null
          employment_status?: string | null
          employment_type?: string | null
          homebase_employee_id?: string | null
          id?: string
          is_in_home?: boolean
          is_telemedicine?: boolean
          medallion_provider_id?: string | null
          name: string
          npi?: string | null
          profession?: string | null
          readiness_status?: string
          shift_types?: string[]
          source?: string | null
          updated_at?: string
        }
        Update: {
          active?: boolean
          athena_provider_id?: string | null
          created_at?: string
          ehr_activation_status?: string
          email?: string | null
          employment_status?: string | null
          employment_type?: string | null
          homebase_employee_id?: string | null
          id?: string
          is_in_home?: boolean
          is_telemedicine?: boolean
          medallion_provider_id?: string | null
          name?: string
          npi?: string | null
          profession?: string | null
          readiness_status?: string
          shift_types?: string[]
          source?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      recommendations_daily: {
        Row: {
          category: string
          computed_at: string
          date: string
          id: string
          payload: Json
        }
        Insert: {
          category: string
          computed_at?: string
          date: string
          id?: string
          payload: Json
        }
        Update: {
          category?: string
          computed_at?: string
          date?: string
          id?: string
          payload?: Json
        }
        Relationships: []
      }
      recommendations_monthly: {
        Row: {
          category: string
          computed_at: string
          forecast_run_id: string | null
          id: string
          month: string
          payload: Json
        }
        Insert: {
          category: string
          computed_at?: string
          forecast_run_id?: string | null
          id?: string
          month: string
          payload: Json
        }
        Update: {
          category?: string
          computed_at?: string
          forecast_run_id?: string | null
          id?: string
          month?: string
          payload?: Json
        }
        Relationships: []
      }
      shift_recommendations: {
        Row: {
          assigned_state: string | null
          created_at: string | null
          decision_run_id: string
          end_min: number
          homebase_shift_id: string | null
          hours: number
          id: string
          notes: string | null
          provider_id: string | null
          provider_name: string
          publish_status: string
          published_at: string | null
          published_by: string | null
          ehr_posted_at: string | null
          ehr_posted_by: string | null
          recommendation: string
          recommendation_reason: string | null
          shift_date: string
          shift_type: string
          start_min: number
          submission_id: string
          target_month: string
          updated_at: string | null
        }
        Insert: {
          assigned_state?: string | null
          created_at?: string | null
          decision_run_id: string
          end_min: number
          homebase_shift_id?: string | null
          hours: number
          id?: string
          notes?: string | null
          provider_id?: string | null
          provider_name: string
          publish_status?: string
          published_at?: string | null
          published_by?: string | null
          recommendation: string
          recommendation_reason?: string | null
          shift_date: string
          shift_type: string
          start_min: number
          submission_id: string
          target_month: string
          updated_at?: string | null
        }
        Update: {
          assigned_state?: string | null
          created_at?: string | null
          decision_run_id?: string
          end_min?: number
          homebase_shift_id?: string | null
          hours?: number
          id?: string
          notes?: string | null
          provider_id?: string | null
          provider_name?: string
          publish_status?: string
          published_at?: string | null
          published_by?: string | null
          ehr_posted_at?: string | null
          ehr_posted_by?: string | null
          recommendation?: string
          recommendation_reason?: string | null
          shift_date?: string
          shift_type?: string
          start_min?: number
          submission_id?: string
          target_month?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      schedule_submissions: {
        Row: {
          accepted_hours: number | null
          created_at: string
          decided_at: string | null
          decision_notes: string | null
          decision_run_id: string | null
          decision_status: string
          declined_hours: number | null
          effective_hours_used_for_forecast: number | null
          hours_changed_by_validation: number | null
          hours_removed_for_duplicates: number | null
          hours_removed_for_unavailability: number | null
          id: string
          intervals_auto_corrected: number | null
          intervals_needing_review: number | null
          jotform_submission_id: string
          normalized_requested_hours: number | null
          normalized_slots: Json | null
          parsed_shifts: Json | null
          provider_id: string | null
          provider_name: string
          raw_answers: Json
          raw_requested_hours: number | null
          submitted_at: string
          target_month: string
          updated_at: string
          validation_status: string | null
          validation_summary: Json | null
          validation_warnings: Json | null
        }
        Insert: {
          accepted_hours?: number | null
          created_at?: string
          decided_at?: string | null
          decision_notes?: string | null
          decision_run_id?: string | null
          decision_status?: string
          declined_hours?: number | null
          effective_hours_used_for_forecast?: number | null
          hours_changed_by_validation?: number | null
          hours_removed_for_duplicates?: number | null
          hours_removed_for_unavailability?: number | null
          id?: string
          intervals_auto_corrected?: number | null
          intervals_needing_review?: number | null
          jotform_submission_id: string
          normalized_requested_hours?: number | null
          normalized_slots?: Json | null
          parsed_shifts?: Json | null
          provider_id?: string | null
          provider_name: string
          raw_answers: Json
          raw_requested_hours?: number | null
          submitted_at: string
          target_month: string
          updated_at?: string
          validation_status?: string | null
          validation_summary?: Json | null
          validation_warnings?: Json | null
        }
        Update: {
          accepted_hours?: number | null
          created_at?: string
          decided_at?: string | null
          decision_notes?: string | null
          decision_run_id?: string | null
          decision_status?: string
          declined_hours?: number | null
          effective_hours_used_for_forecast?: number | null
          hours_changed_by_validation?: number | null
          hours_removed_for_duplicates?: number | null
          hours_removed_for_unavailability?: number | null
          id?: string
          intervals_auto_corrected?: number | null
          intervals_needing_review?: number | null
          jotform_submission_id?: string
          normalized_requested_hours?: number | null
          normalized_slots?: Json | null
          parsed_shifts?: Json | null
          provider_id?: string | null
          provider_name?: string
          raw_answers?: Json
          raw_requested_hours?: number | null
          submitted_at?: string
          target_month?: string
          updated_at?: string
          validation_status?: string | null
          validation_summary?: Json | null
          validation_warnings?: Json | null
        }
        Relationships: []
      }
      shifts: {
        Row: {
          date: string
          end_time: string
          homebase_shift_id: string
          hours: number
          id: string
          location_id: string | null
          provider_id: string | null
          role: string | null
          source: string
          start_time: string
          state: string | null
          synced_at: string
        }
        Insert: {
          date: string
          end_time: string
          homebase_shift_id: string
          hours: number
          id?: string
          location_id?: string | null
          provider_id?: string | null
          role?: string | null
          source?: string
          start_time: string
          state?: string | null
          synced_at?: string
        }
        Update: {
          date?: string
          end_time?: string
          homebase_shift_id?: string
          hours?: number
          id?: string
          location_id?: string | null
          provider_id?: string | null
          role?: string | null
          source?: string
          start_time?: string
          state?: string | null
          synced_at?: string
        }
        Relationships: []
      }
      sla_daily: {
        Row: {
          available_slots: number
          computed_at: string
          daily_target: number
          date: string
          monthly_visits: number | null
          ratio: number
          sla_flagged: boolean
          sla_pct: number | null
          state: string
          status: string
        }
        Insert: {
          available_slots: number
          computed_at?: string
          daily_target: number
          date: string
          monthly_visits?: number | null
          ratio: number
          sla_flagged?: boolean
          sla_pct?: number | null
          state: string
          status: string
        }
        Update: {
          available_slots?: number
          computed_at?: string
          daily_target?: number
          date?: string
          monthly_visits?: number | null
          ratio?: number
          sla_flagged?: boolean
          sla_pct?: number | null
          state?: string
          status?: string
        }
        Relationships: []
      }
      state_demand_targets: {
        Row: {
          computed_at: string
          daily_target_slots: number
          forecast_run_id: string | null
          growth_multiplier: number
          month: string
          monthly_hours_target: number
          monthly_visits_target: number
          state: string
        }
        Insert: {
          computed_at?: string
          daily_target_slots: number
          forecast_run_id?: string | null
          growth_multiplier?: number
          month: string
          monthly_hours_target: number
          monthly_visits_target: number
          state: string
        }
        Update: {
          computed_at?: string
          daily_target_slots?: number
          forecast_run_id?: string | null
          growth_multiplier?: number
          month?: string
          monthly_hours_target?: number
          monthly_visits_target?: number
          state?: string
        }
        Relationships: []
      }
      utilization_summary: {
        Row: {
          computed_at: string
          data_source: string
          month_avg_pct: number | null
          provider_id: string
          week_max_pct: number | null
        }
        Insert: {
          computed_at?: string
          data_source?: string
          month_avg_pct?: number | null
          provider_id: string
          week_max_pct?: number | null
        }
        Update: {
          computed_at?: string
          data_source?: string
          month_avg_pct?: number | null
          provider_id?: string
          week_max_pct?: number | null
        }
        Relationships: []
      }
    }
    Views: {
      v_monthly_cost_per_visit: {
        Row: {
          approx_cost_per_completed_visit: number | null
          approx_cost_per_scheduled_appointment: number | null
          completed_appointments: number | null
          completion_rate: number | null
          month_start: string | null
          total_appointments: number | null
          total_wages_paid: number | null
        }
        Relationships: []
      }
      v_monthly_demand: {
        Row: {
          month: string | null
          state: string | null
          total_visits: number | null
        }
        Relationships: []
      }
      v_provider_current_rate: {
        Row: {
          active: boolean | null
          effective_from: string | null
          email: string | null
          homebase_employee_id: string | null
          hourly_rate: number | null
          name: string | null
          profession: string | null
          provider_id: string | null
          rate_role: string | null
          rate_source: string | null
        }
        Relationships: []
      }
      v_provider_shift_summary: {
        Row: {
          confirmed_count: number | null
          cut_count: number | null
          cut_hours: number | null
          pending_publish: number | null
          provider_id: string | null
          provider_name: string | null
          publish_count: number | null
          publish_hours: number | null
          published_count: number | null
          target_month: string | null
          total_shifts: number | null
        }
        Relationships: []
      }
      v_state_blended_rate: {
        Row: {
          avg_hourly_rate: number | null
          licensed_provider_count: number | null
          max_hourly_rate: number | null
          median_hourly_rate: number | null
          min_hourly_rate: number | null
          rated_provider_count: number | null
          state: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      get_activation_candidates: {
        Args: {
          candidate_limit?: number
          deficit_states: string[]
          shift_type_filter?: string[]
          util_threshold?: number
        }
        Returns: {
          data_source: string
          ehr_activation_status: string
          email: string
          provider_id: string
          provider_name: string
          readiness_status: string
          score: number
          state: string
          utilization_pct: number
        }[]
      }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

export type ClinOpsTables<T extends keyof ClinOpsDatabase['public']['Tables']> =
  ClinOpsDatabase['public']['Tables'][T]['Row']

export type ClinOpsViews<T extends keyof ClinOpsDatabase['public']['Views']> =
  ClinOpsDatabase['public']['Views'][T]['Row']
